Repository ansible-collections/ibm_zos_core, pull requests merged in 2020-07, with the labels that each got.

#128 Encode util close file descriptor
  plugins/module_utils/encode.py
Labels: bugfix

#120 Feature/2298/zos raw
  playbooks/zos-collection-sample-v2.yaml
  playbooks/zos-collection-sample.yaml
  plugins/module_utils/backup.py
  plugins/module_utils/better_arg_parser.py
  plugins/module_utils/data_set.py
  plugins/module_utils/dd_statement.py
  plugins/module_utils/import_handler.py
  plugins/module_utils/zos_mvs_raw.py
  plugins/modules/zos_data_set.py
  plugins/modules/zos_mvs_raw.py
  plugins/modules/zos_ping.rexx
  tests/functional/modules/test_zos_copy_func.py
  tests/functional/modules/test_zos_data_set_func.py
  tests/functional/modules/test_zos_encode_func.py
  tests/functional/modules/test_zos_fetch_func.py
  tests/functional/modules/test_zos_mvs_raw_func.py
  tests/helpers/zos_lineinfile_helper.py
  tests/helpers/ztest.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
  tests/unit/test_zos_mvs_raw_unit.py
Labels: enhancement

#131 Update configuration vars in doc and yml
  docs/source/playbooks.rst
  playbooks/group_vars/all.yml
Labels: documentation

#132 remove ZOAU Python API deps for zos_operator
  plugins/modules/zos_operator.py
Labels: bugfix

#135 upload helper wrapper and fix usage
  plugins/module_utils/ansible_module.py
  plugins/module_utils/backup.py
  plugins/module_utils/copy.py
  plugins/module_utils/data_set.py
  plugins/module_utils/encode.py
  plugins/module_utils/job.py
  plugins/module_utils/vtoc.py
  plugins/module_utils/zos_mvs_raw.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_encode.py
  plugins/modules/zos_mvs_raw.py
  plugins/modules/zos_operator.py
  tests/unit/test_zos_mvs_raw_unit.py
Labels: bugfix

#134 zos_copy Update
  plugins/action/zos_copy.py
  plugins/module_utils/backup.py
  plugins/module_utils/copy.py
  plugins/module_utils/data_set.py
  plugins/module_utils/mvs_cmd.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_encode.py
  plugins/modules/zos_fetch.py
  tests/functional/modules/test_zos_copy_func.py
Labels: bugfix, documentation, enhancement

#136 Content/2516/release doc update
  docs/source/community_guides_docs/zos_ansible_module_testing.rst
  docs/source/modules/zos_copy.rst
  docs/source/modules/zos_data_set.rst
  docs/source/modules/zos_encode.rst
  docs/source/modules/zos_fetch.rst
  docs/source/modules/zos_job_output.rst
  docs/source/modules/zos_job_query.rst
  docs/source/modules/zos_job_submit.rst
  docs/source/modules/zos_lineinfile.rst
  docs/source/modules/zos_mvs_raw.rst
  docs/source/modules/zos_operator.rst
  docs/source/modules/zos_operator_action_query.rst
  docs/source/modules/zos_ping.rst
  docs/source/modules/zos_tso_command.rst
  docs/source/playbooks.rst
  docs/source/release_notes.rst
  docs/source/requirements.rst
  docs/templates/module.rst.j2
  galaxy.yml
  playbooks/files/UPTIME
  playbooks/zos-collection-sample-v2.yaml
  playbooks/zos-collection-sample-v3.yaml
  plugins/modules/zos_copy.py
  plugins/modules/zos_mvs_raw.py
Labels: documentation

#137 Release v1.2.0 beta.1
  docs/Makefile
  docs/source/community_guides_docs/zos_ansible_module_testing.rst
  docs/source/conf.py
  docs/source/installation.rst
  docs/source/modules/zos_copy.rst
  docs/source/modules/zos_data_set.rst
  docs/source/modules/zos_encode.rst
  docs/source/modules/zos_fetch.rst
  docs/source/modules/zos_lineinfile.rst
  docs/source/modules/zos_mvs_raw.rst
  docs/source/playbooks.rst
  docs/source/release_notes.rst
  docs/source/requirements.rst
  docs/templates/module.rst.j2
  galaxy.yml
  playbooks/files/UPTIME
  playbooks/group_vars/all.yml
  playbooks/zos-collection-sample-v2.yaml
  playbooks/zos-collection-sample-v3.yaml
  playbooks/zos-collection-sample.yaml
  plugins/action/zos_copy.py
  plugins/action/zos_fetch.py
  plugins/module_utils/ansible_module.py
  plugins/module_utils/backup.py
  plugins/module_utils/better_arg_parser.py
  plugins/module_utils/copy.py
  plugins/module_utils/data_set.py
  plugins/module_utils/dd_statement.py
  plugins/module_utils/encode.py
  plugins/module_utils/import_handler.py
  plugins/module_utils/job.py
  plugins/module_utils/mvs_cmd.py
  plugins/module_utils/vtoc.py
  plugins/module_utils/zos_mvs_raw.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_data_set.py
  plugins/modules/zos_encode.py
  plugins/modules/zos_fetch.py
  plugins/modules/zos_job_query.py
  plugins/modules/zos_lineinfile.py
  plugins/modules/zos_mvs_raw.py
  plugins/modules/zos_operator.py
  plugins/modules/zos_ping.rexx
  tests/functional/modules/test_zos_copy_func.py
  tests/functional/modules/test_zos_data_set_func.py
  tests/functional/modules/test_zos_encode_func.py
  tests/functional/modules/test_zos_fetch_func.py
  tests/functional/modules/test_zos_lineinfile_func.py
  tests/functional/modules/test_zos_mvs_raw_func.py
  tests/helpers/zos_lineinfile_helper.py
  tests/helpers/ztest.py
  tests/pytest.ini
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
  tests/unit/test_zos_mvs_raw_unit.py
Labels: release

#138 Fix E231: missing whitespace
  docs/source/conf.py
Labels: documentation

#141 Specify SFTP port for fetch and copy
  plugins/action/zos_copy.py
  plugins/action/zos_fetch.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_fetch.py
  tests/functional/modules/test_zos_copy_func.py
  tests/functional/modules/test_zos_fetch_func.py
Labels: enhancement

#142 Feature/dependency discovery
  playbooks/filter_plugins/command-strings.py
  playbooks/filter_plugins/determine-paths.py
  playbooks/host-setup.yaml
  playbooks/tasks/choose-python.yaml
  playbooks/tasks/choose-zoau.yaml
  playbooks/templates/host-vars.j2
  playbooks/templates/inventory.j2
  playbooks/templates/test-vars.j2
Labels: enhancement

#143 Redundant data set util
  plugins/module_utils/data_set.py
  plugins/module_utils/data_set_utils.py
Labels: update

#144 Rename backup_file to backup_name
  docs/source/modules/zos_copy.rst
  docs/source/modules/zos_encode.rst
  docs/source/modules/zos_lineinfile.rst
  plugins/action/zos_copy.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_encode.py
  plugins/modules/zos_lineinfile.py
  tests/functional/modules/test_zos_copy_func.py
  tests/functional/modules/test_zos_encode_func.py
Labels: update
