Repository ansible-collections/ibm_zos_core, pull requests merged in 2020-10, with the labels that each got.

#202 fail on non-zero zoau copy return code
  plugins/modules/zos_copy.py
  tests/functional/modules/test_zos_copy_func.py
Labels: bugfix

#198 Feature/2636/zos backup restore
  plugins/module_utils/better_arg_parser.py
  plugins/module_utils/data_set.py
  plugins/modules/zos_backup_restore.py
  tests/functional/modules/test_zos_backup_restore.py
  tests/functional/modules/test_zos_job_submit_func.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
  tests/unit/test_zos_backup_restore_unit.py
Labels: New Module

#205 Release v1.3.0 beta.1
  docs/source/modules/zos_apf.rst
  docs/source/modules/zos_backup_restore.rst
  docs/source/modules/zos_blockinfile.rst
  docs/source/modules/zos_copy.rst
  docs/source/modules/zos_data_set.rst
  docs/source/modules/zos_find.rst
  docs/source/playbooks.rst
  docs/source/release_notes.rst
  docs/source/requirements-single.rst
  docs/source/requirements_managed.rst
  plugins/action/zos_copy.py
  plugins/module_utils/backup.py
  plugins/module_utils/better_arg_parser.py
  plugins/module_utils/data_set.py
  plugins/module_utils/dd_statement.py
  plugins/module_utils/encode.py
  plugins/modules/zos_apf.py
  plugins/modules/zos_backup_restore.py
  plugins/modules/zos_blockinfile.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_data_set.py
  plugins/modules/zos_encode.py
  plugins/modules/zos_fetch.py
  plugins/modules/zos_find.py
  plugins/modules/zos_job_output.py
  plugins/modules/zos_job_query.py
  plugins/modules/zos_job_submit.py
  plugins/modules/zos_lineinfile.py
  plugins/modules/zos_mvs_raw.py
  plugins/modules/zos_operator.py
  plugins/modules/zos_operator_action_query.py
  plugins/modules/zos_tso_command.py
  tests/functional/modules/test_zos_apf_func.py
  tests/functional/modules/test_zos_backup_restore.py
  tests/functional/modules/test_zos_blockinfile_func.py
  tests/functional/modules/test_zos_copy_func.py
  tests/functional/modules/test_zos_data_set_func.py
  tests/functional/modules/test_zos_find_func.py
  tests/functional/modules/test_zos_job_submit_func.py
  tests/functional/modules/test_zos_tso_command_func.py
  tests/helpers/zos_blockinfile_helper.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
  tests/unit/test_zos_backup_restore_unit.py
Labels: release
