Repository ansible-collections/ibm_zos_core, pull requests merged in 2020-08, with the labels that each got.

#147 Bugfix/zos_copy record format
  plugins/modules/zos_copy.py
Labels: bugfix

#149 Bugfix/148/accept all valid data set name characters
  plugins/modules/zos_job_submit.py
  tests/functional/modules/test_zos_job_submit_func.py
Labels: bugfix

#151 improve cleanup
  tests/conftest.py
Labels: update

#152 Update file extensions in host-setup.yaml
  playbooks/host-setup.yaml
  playbooks/templates/host-vars.j2
  playbooks/templates/test-vars.j2
Labels: bugfix

#153 copy/fetch: Ignore stderr
  docs/source/modules/zos_copy.rst
  docs/source/modules/zos_fetch.rst
  plugins/action/zos_copy.py
  plugins/action/zos_fetch.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_fetch.py
Labels: enhancement, update

#154 Bugfix: zos operator action query not returning all outstanding messages
  plugins/modules/zos_operator_action_query.py
Labels: bugfix

#155 Changes to support single source doc site
  docs/Makefile
  docs/ansible_content.rst
  docs/scripts/post-doc-gen.sh
  docs/scripts/pre-doc-gen.sh
  docs/source/community_guides.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/license.rst
  docs/source/modules.rst
  docs/source/playbook_config_setup.rst
  docs/source/playbook_group_vars.rst
  docs/source/playbook_inventory.rst
  docs/source/playbook_run.rst
  docs/source/playbooks.rst
  docs/source/plugins.rst
  docs/source/quickstart.rst
  docs/source/requirements.rst
  docs/source/requirements_managed.rst
  docs/source/supplementary.rst
  docs/zos-collection-index.rst
Labels: documentation

#145 Changes to support single source doc site
  docs/Makefile
  docs/ansible_content.rst
  docs/scripts/post-doc-gen.sh
  docs/scripts/pre-doc-gen.sh
  docs/source/community_guides.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/license.rst
  docs/source/modules.rst
  docs/source/playbook_config_setup.rst
  docs/source/playbook_group_vars.rst
  docs/source/playbook_inventory.rst
  docs/source/playbook_run.rst
  docs/source/playbooks.rst
  docs/source/plugins.rst
  docs/source/quickstart.rst
  docs/source/requirements.rst
  docs/source/requirements_managed.rst
  docs/source/supplementary.rst
  docs/zos-collection-index.rst
Labels: documentation

#156 Add verbose support and steplib fix
  plugins/module_utils/dd_statement.py
  plugins/modules/zos_mvs_raw.py
Labels: bugfix

#158 Content/3397/update docs
  docs/source/modules/zos_copy.rst
  docs/source/modules/zos_fetch.rst
  docs/source/modules/zos_mvs_raw.rst
  docs/source/playbook_config_setup.rst
  docs/source/release_notes.rst
  playbooks/host-setup.yaml
  plugins/modules/zos_mvs_raw.py
Labels: documentation

#157 Content/3397/update docs
  docs/source/modules/zos_copy.rst
  docs/source/modules/zos_fetch.rst
  docs/source/modules/zos_mvs_raw.rst
  docs/source/playbook_config_setup.rst
  docs/source/release_notes.rst
  playbooks/host-setup.yaml
  plugins/modules/zos_mvs_raw.py
Labels: documentation

#162 Update/release v1.2.0 beta.2
  docs/ansible_content.rst
  docs/source/modules/zos_copy.rst
  docs/source/modules/zos_encode.rst
  docs/source/modules/zos_fetch.rst
  docs/source/modules/zos_lineinfile.rst
  docs/source/modules/zos_mvs_raw.rst
  docs/source/playbook_config_setup.rst
  docs/source/release_notes.rst
  galaxy.yml
  playbooks/filter_plugins/command-strings.py
  playbooks/filter_plugins/determine-paths.py
  playbooks/host-setup.yaml
  playbooks/tasks/choose-python.yaml
  playbooks/tasks/choose-zoau.yaml
  playbooks/templates/host-vars.j2
  playbooks/templates/inventory.j2
  playbooks/templates/test-vars.j2
  plugins/action/zos_copy.py
  plugins/action/zos_fetch.py
  plugins/module_utils/data_set.py
  plugins/module_utils/data_set_utils.py
  plugins/module_utils/dd_statement.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_encode.py
  plugins/modules/zos_fetch.py
  plugins/modules/zos_job_submit.py
  plugins/modules/zos_lineinfile.py
  plugins/modules/zos_mvs_raw.py
  plugins/modules/zos_operator_action_query.py
  tests/conftest.py
  tests/functional/modules/test_zos_copy_func.py
  tests/functional/modules/test_zos_encode_func.py
  tests/functional/modules/test_zos_fetch_func.py
  tests/functional/modules/test_zos_job_submit_func.py
Labels: bug, documentation

#163 Release v1.2.0 beta.2
  docs/Makefile
  docs/ansible_content.rst
  docs/scripts/post-doc-gen.sh
  docs/scripts/pre-doc-gen.sh
  docs/source/community_guides.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/license.rst
  docs/source/modules.rst
  docs/source/modules/zos_copy.rst
  docs/source/modules/zos_encode.rst
  docs/source/modules/zos_fetch.rst
  docs/source/modules/zos_lineinfile.rst
  docs/source/modules/zos_mvs_raw.rst
  docs/source/playbook_config_setup.rst
  docs/source/playbook_group_vars.rst
  docs/source/playbook_inventory.rst
  docs/source/playbook_run.rst
  docs/source/playbooks.rst
  docs/source/plugins.rst
  docs/source/quickstart.rst
  docs/source/release_notes.rst
  docs/source/requirements.rst
  docs/source/requirements_managed.rst
  docs/source/supplementary.rst
  docs/zos-collection-index.rst
  galaxy.yml
  playbooks/filter_plugins/command-strings.py
  playbooks/filter_plugins/determine-paths.py
  playbooks/host-setup.yaml
  playbooks/tasks/choose-python.yaml
  playbooks/tasks/choose-zoau.yaml
  playbooks/templates/host-vars.j2
  playbooks/templates/inventory.j2
  playbooks/templates/test-vars.j2
  plugins/action/zos_copy.py
  plugins/action/zos_fetch.py
  plugins/module_utils/data_set.py
  plugins/module_utils/data_set_utils.py
  plugins/module_utils/dd_statement.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_encode.py
  plugins/modules/zos_fetch.py
  plugins/modules/zos_job_submit.py
  plugins/modules/zos_lineinfile.py
  plugins/modules/zos_mvs_raw.py
  plugins/modules/zos_operator_action_query.py
  tests/conftest.py
  tests/functional/modules/test_zos_copy_func.py
  tests/functional/modules/test_zos_encode_func.py
  tests/functional/modules/test_zos_fetch_func.py
  tests/functional/modules/test_zos_job_submit_func.py
Labels: release

#167 add FQCN to action plugins
  plugins/action/zos_copy.py
  plugins/action/zos_fetch.py
  plugins/action/zos_job_submit.py
Labels: bugfix

#168 Release v1.2.0 beta.3
  docs/source/release_notes.rst
  galaxy.yml
  plugins/action/zos_copy.py
  plugins/action/zos_fetch.py
  plugins/action/zos_job_submit.py
Labels: bug, release

#170 Release and updates to v1.2.0 beta.2
  docs/Makefile
  docs/ansible_content.rst
  docs/scripts/auto-doc-gen.sh
  docs/scripts/post-doc-gen.sh
  docs/scripts/pre-doc-gen.sh
  docs/source/community_guides.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/license.rst
  docs/source/modules.rst
  docs/source/modules/zos_copy.rst
  docs/source/modules/zos_encode.rst
  docs/source/modules/zos_fetch.rst
  docs/source/modules/zos_lineinfile.rst
  docs/source/modules/zos_mvs_raw.rst
  docs/source/playbook_config_setup.rst
  docs/source/playbook_group_vars.rst
  docs/source/playbook_inventory.rst
  docs/source/playbook_run.rst
  docs/source/playbooks-single.rst
  docs/source/playbooks.rst
  docs/source/plugins.rst
  docs/source/quickstart.rst
  docs/source/release_notes.rst
  docs/source/requirements-single.rst
  docs/source/requirements.rst
  docs/source/requirements_managed.rst
  docs/source/supplementary.rst
  docs/zos-collection-index.rst
  galaxy.yml
  playbooks/filter_plugins/command-strings.py
  playbooks/filter_plugins/determine-paths.py
  playbooks/host-setup.yaml
  playbooks/tasks/choose-python.yaml
  playbooks/tasks/choose-zoau.yaml
  playbooks/templates/host-vars.j2
  playbooks/templates/inventory.j2
  playbooks/templates/test-vars.j2
  plugins/action/zos_copy.py
  plugins/action/zos_fetch.py
  plugins/module_utils/data_set.py
  plugins/module_utils/data_set_utils.py
  plugins/module_utils/dd_statement.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_encode.py
  plugins/modules/zos_fetch.py
  plugins/modules/zos_job_submit.py
  plugins/modules/zos_lineinfile.py
  plugins/modules/zos_mvs_raw.py
  plugins/modules/zos_operator_action_query.py
  tests/conftest.py
  tests/functional/modules/test_zos_copy_func.py
  tests/functional/modules/test_zos_encode_func.py
  tests/functional/modules/test_zos_fetch_func.py
  tests/functional/modules/test_zos_job_submit_func.py
Labels: release

#169 Copy + Fetch Update
  docs/source/modules/zos_copy.rst
  docs/source/modules/zos_fetch.rst
  plugins/action/zos_copy.py
  plugins/action/zos_fetch.py
  plugins/module_utils/data_set.py
  plugins/module_utils/encode.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_fetch.py
Labels: bugfix, enhancement

#171 Release and updates to v1.2.0 beta.3
  docs/source/conf.py
  plugins/action/zos_fetch.py
Labels: documentation

#175 update job utility to handle various system configurations
  plugins/module_utils/job.py
Labels: bugfix

#173 Default MVS charset should be IBM-037
  plugins/action/zos_copy.py
  plugins/action/zos_fetch.py
  plugins/module_utils/encode.py
  plugins/module_utils/system.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_fetch.py
  tests/conftest.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: bugfix

#174 Update/647/determine system default encoding if not provided
  plugins/modules/zos_job_submit.py
Labels: update
