Repository ansible-collections/ibm_zos_core, pull requests merged in 2020-09, with the labels that each got.

#179 Update/2616/zos encode return backup file
  plugins/modules/zos_encode.py
  tests/functional/modules/test_zos_encode_func.py
Labels: bugfix, enhancement

#172 release notes and url updates
  docs/source/release_notes.rst
  docs/source/requirements_managed.rst
  docs/templates/breadcrumbs.html
Labels: documentation

#182 Bugfix/3696/zero values break parameters
  plugins/module_utils/data_set.py
  plugins/modules/zos_data_set.py
  tests/functional/modules/test_zos_data_set_func.py
Labels: bugfix

#181 Feature/2810/copy multiple members
  plugins/module_utils/system.py
  plugins/modules/zos_copy.py
  tests/functional/modules/test_zos_copy_func.py
Labels: enhancement

#185 Release v1.2.0 beta.4
  docs/source/conf.py
  docs/source/modules/zos_copy.rst
  docs/source/modules/zos_encode.rst
  docs/source/modules/zos_fetch.rst
  docs/source/modules/zos_job_submit.rst
  docs/source/plugins.rst
  docs/source/release_notes.rst
  docs/source/requirements_managed.rst
  docs/templates/breadcrumbs.html
  galaxy.yml
  playbooks/host-setup.yaml
  plugins/action/zos_copy.py
  plugins/action/zos_fetch.py
  plugins/action/zos_job_submit.py
  plugins/module_utils/data_set.py
  plugins/module_utils/encode.py
  plugins/module_utils/job.py
  plugins/module_utils/system.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_data_set.py
  plugins/modules/zos_encode.py
  plugins/modules/zos_fetch.py
  plugins/modules/zos_job_submit.py
  tests/conftest.py
  tests/functional/modules/test_zos_copy_func.py
  tests/functional/modules/test_zos_data_set_func.py
  tests/functional/modules/test_zos_encode_func.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: release

#188 Release v1.2.1
  docs/source/conf.py
  docs/source/release_notes.rst
  galaxy.yml
  plugins/module_utils/encode.py
  plugins/module_utils/system.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_fetch.py
Labels: release

#189 Merge master into dev which diverged during release v1.2.1
  README.md
  docs/ansible_content.rst
  docs/scripts/auto-doc-gen.sh
  docs/source/conf.py
  docs/source/index.rst
  docs/source/playbook_config_setup.rst
  docs/source/playbook_group_vars.rst
  docs/source/playbook_inventory.rst
  docs/source/playbook_run.rst
  docs/source/playbooks-single.rst
  docs/source/playbooks.rst
  docs/source/release_notes.rst
  docs/source/requirements-single.rst
  docs/source/requirements_managed.rst
  galaxy.yml
  playbooks/ansible.cfg
  playbooks/files/HELLO.jcl
  playbooks/files/UPTIME
  playbooks/filter_plugins/command-strings.py
  playbooks/filter_plugins/determine-paths.py
  playbooks/group_vars/all.yml
  playbooks/host-setup.yaml
  playbooks/inventory
  playbooks/tasks/choose-python.yaml
  playbooks/tasks/choose-zoau.yaml
  playbooks/templates/host-vars.j2
  playbooks/templates/inventory.j2
  playbooks/templates/test-vars.j2
  playbooks/zos-collection-sample-v2.yaml
  playbooks/zos-collection-sample-v3.yaml
  playbooks/zos-collection-sample.yaml
  plugins/module_utils/encode.py
  plugins/module_utils/system.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_fetch.py
Labels: bug, documentation

#192 Feature/3303/zfs support allocate and format
  plugins/module_utils/backup.py
  plugins/module_utils/data_set.py
  plugins/module_utils/dd_statement.py
  plugins/module_utils/encode.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_data_set.py
  plugins/modules/zos_encode.py
  plugins/modules/zos_fetch.py
  plugins/modules/zos_job_output.py
  plugins/modules/zos_job_query.py
  plugins/modules/zos_job_submit.py
  plugins/modules/zos_lineinfile.py
  plugins/modules/zos_mvs_raw.py
  plugins/modules/zos_operator.py
  plugins/modules/zos_operator_action_query.py
  plugins/modules/zos_tso_command.py
  tests/functional/modules/test_zos_data_set_func.py
  tests/functional/modules/test_zos_tso_command_func.py
Labels: enhancement, update

#194 fix zos_tso_command
  plugins/modules/zos_tso_command.py
Labels: bugfix

#196 catalog only when we are sure data set exists on volume
  plugins/module_utils/data_set.py
  plugins/modules/zos_data_set.py
Labels: bugfix

#190 Feature/1050/zos find module
  plugins/modules/zos_find.py
  tests/functional/modules/test_zos_find_func.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: enhancement
