Repository ansible-collections/ibm_zos_core, pull requests merged in 2020-05, with the labels that each got.

#75 Documentation updates, corrections and alterations
  plugins/modules/zos_encode.py
Labels: documentation

#80 add out-of-box awx support
  ansible.cfg
  collections/requirements.yml
Labels: enhancement, update

#78 Added encoding supplemental doc
  docs/source/index.rst
  docs/source/supplementary.rst
  plugins/modules/zos_encode.py
  plugins/modules/zos_fetch.py
Labels: documentation

#82 fixed bug and cleaned up code
  plugins/module_utils/vtoc.py
  plugins/modules/zos_data_set.py
Labels: bugfix

#84 Content/static docs docreveiw
  docs/source/community_guides.rst
  docs/source/filters.rst
  docs/source/installation.rst
  docs/source/modules.rst
  docs/source/playbooks.rst
  docs/source/plugins.rst
  docs/source/quickstart.rst
  docs/source/release_notes.rst
  docs/source/requirements.rst
Labels: documentation

#83 Add binary support for copying across USS and MVS
  plugins/module_utils/copy.py
Labels: update

#86 Minor updates in install,quickstart, and req pages
  docs/source/installation.rst
  docs/source/quickstart.rst
  docs/source/requirements.rst
Labels: documentation, update

#87 Updated make file with comments and recover from failure
  docs/Makefile
Labels: documentation, update

#85 Update Backup util (mvs_file_backup)
  plugins/module_utils/backup.py
  plugins/module_utils/encode.py
  plugins/modules/zos_encode.py
  tests/functional/modules/test_zos_encode_func.py
Labels: bugfix

#89 Udpate the restructured text to reflect version release
  docs/source/modules/zos_data_set.rst
  docs/source/modules/zos_encode.rst
  docs/source/modules/zos_fetch.rst
  docs/source/modules/zos_job_output.rst
  docs/source/modules/zos_job_query.rst
  docs/source/modules/zos_job_submit.rst
  docs/source/modules/zos_operator.rst
  docs/source/modules/zos_operator_action_query.rst
  docs/source/modules/zos_tso_command.rst
Labels: documentation

#88 minor fixes and additional tests for zos_encode
  plugins/module_utils/backup.py
  plugins/modules/zos_encode.py
  tests/functional/modules/test_zos_encode_func.py
Labels: bugfix

#92 removed Jobs.submit usage due to invalid response
  plugins/modules/zos_job_submit.py
Labels: bugfix

#93 removed Jobs.submit usage due to invalid response
  plugins/modules/zos_job_submit.py
Labels: bugfix

#94 Update to galaxy.yml to exclude files
  galaxy.yml
Labels: update

#97 Fixes spacing in RETURN values and formatting
  docs/templates/module.rst.j2
Labels: bug, documentation

#98 Bugfix MVS Backup
  plugins/module_utils/backup.py
Labels: bugfix

#99 fix job utility to work on all z/OS systems
  plugins/module_utils/job.py
Labels: bugfix

#100 Shinx and sphinx-versioning support and updates
  docs/Makefile
  docs/source/conf.py
Labels: documentation, update

#102 Correct and update the installation of a pre-release
  docs/source/installation.rst
  plugins/modules/zos_encode.py
  plugins/modules/zos_fetch.py
  plugins/modules/zos_job_submit.py
Labels: documentation, update

#104 Update data set utils
  plugins/module_utils/data_set.py
  plugins/modules/zos_encode.py
  plugins/modules/zos_fetch.py
Labels: update

#107 Update/1979/default encoding value
  plugins/action/zos_fetch.py
  plugins/modules/zos_job_submit.py
  tests/functional/modules/test_zos_fetch_func.py
Labels: documentation, enhancement

#108 Bugfix/case conversion fix zos tso command
  plugins/modules/zos_tso_command.py
  tests/functional/modules/test_zos_tso_command_func.py
Labels: bugfix

#109 Added index file to support shared doc site
  docs/zos-collection-index.rst
Labels: documentation
