Repository ansible-collections/ibm_zos_core, pull requests merged in 2020-06, with the labels that each got.

#110 Bugfix/78/fetch-encode
  plugins/modules/zos_fetch.py
Labels: bugfix

#112 fix issue when no default encoding specified
  plugins/modules/zos_job_submit.py
Labels: bugfix

#105 Feature/26/ansible zos copy module
  plugins/action/zos_copy.py
  plugins/modules/zos_copy.py
  tests/functional/modules/test_zos_copy_func.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: enhancement, under review

#111 Feature/1089/zos lineinfile
  playbooks/zos-collection-sample.yaml
  plugins/modules/zos_encode.py
  plugins/modules/zos_fetch.py
  plugins/modules/zos_lineinfile.py
  tests/functional/modules/test_zos_lineinfile_func.py
  tests/helpers/zos_lineinfile_helper.py
  tests/pytest.ini
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: enhancement, under review

#113 Content/1067/community doc
  README.md
  docs/source/community_guides.rst
  docs/source/community_guides_docs/better_arg_parser.rst
  docs/source/community_guides_docs/zos_ansible_module_testing.rst
  docs/source/index.rst
  docs/source/playbooks.rst
  docs/source/release_notes.rst
  docs/source/requirements.rst
  playbooks/group_vars/all.yml
  plugins/modules/zos_ping.rexx
Labels: documentation

#116 update/78/fetch-doc-update
  plugins/modules/zos_fetch.py
Labels: documentation

#118 Doc review
  docs/source/playbooks.rst
  playbooks/files/HELLO.jcl
  playbooks/group_vars/all.yml
  playbooks/zos-collection-sample-v2.yaml
  playbooks/zos-collection-sample.yaml
Labels: documentation

#121 fix unsupported options python 2.6
  plugins/action/zos_fetch.py
  plugins/module_utils/better_arg_parser.py
Labels: bugfix

#127 Add system info to job query
  plugins/module_utils/job.py
  plugins/modules/zos_job_query.py
Labels: enhancement
