Repository ansible-collections/ibm_zos_core, pull requests merged in 2020-04, with the labels that each got.

#45 Initial commit for module zos_operator
  plugins/modules/zos_operator.py
  tests/functional/modules/test_zos_operator_func.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
  tests/unit/test_zos_operator_unit.py
Labels: enhancement, see comments

#55 fixed PATH
  playbooks/group_vars/all.yml
Labels: bugfix

#56 Update/973/add new supported data set characters betterargparser
  plugins/module_utils/better_arg_parser.py
  tests/functional/module_utils/test_arg_parser.py
Labels: update

#57 Bugfix/822/data set exists
  plugins/module_utils/data_set_utils.py
Labels: bugfix

#43 Initial commit for module zos_operator_action_query
  plugins/modules/zos_operator_action_query.py
  tests/functional/modules/test_zos_operator_action_query_func.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
  tests/unit/test_zos_operator_action_query_unit.py
Labels: enhancement, see comments

#58 Check for data set member existence
  plugins/module_utils/data_set_utils.py
Labels: enhancement

#60 bugfix for job name capture group
  plugins/modules/zos_operator_action_query.py
Labels: bugfix

#61 Better ZOAU import missing messages
  plugins/module_utils/import_handler.py
  plugins/modules/zos_data_set.py
  plugins/modules/zos_job_query.py
  plugins/modules/zos_job_submit.py
  plugins/modules/zos_operator.py
  plugins/modules/zos_operator_action_query.py
Labels: enhancement, update

#63 changed behavior on failure
  plugins/modules/zos_operator_action_query.py
  tests/functional/modules/test_zos_operator_action_query_func.py
Labels: update

#64 Bugfix/1661 & 1704 fix query of job for different user zos_job_submit and zos_job_action_query
  plugins/module_utils/job.py
  plugins/modules/zos_job_output.py
  plugins/modules/zos_job_query.py
  plugins/modules/zos_job_submit.py
  tests/conftest.py
Labels: bugfix

#46 Initial module zos_tso_command
  plugins/modules/zos_tso_command.py
  tests/functional/modules/test_zos_tso_command_func.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: enhancement, see comments

#7 z/OS Fetch Module
  plugins/action/zos_fetch.py
  plugins/modules/zos_fetch.py
  tests/functional/modules/test_zos_fetch_func.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: enhancement, under review

#66 enhanced zoau import error message
  plugins/modules/zos_encode.py
  plugins/modules/zos_fetch.py
Labels: enhancement, update

#67 Added new playbook for latest module collection and a filter
  playbooks/zos-collection-sample-v2.yaml
  plugins/filter/__init__.py
  plugins/filter/wtor.py
Labels: documentation

#68 Use encode util to convert encoding
  plugins/modules/zos_fetch.py
Labels: update

#69 Content/58/update documentation for release
  README.md
  docs/Makefile
  docs/source/filters.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/modules.rst
  docs/source/playbooks.rst
  docs/source/release_notes.rst
  docs/source/requirements.rst
  playbooks/ansible.cfg
  playbooks/files/HELLO.jcl
  playbooks/group_vars/all.yml
  playbooks/inventory
  playbooks/zos-collection-sample-v2.yaml
  playbooks/zos-collection-sample.yaml
  plugins/modules/zos_encode.py
  plugins/modules/zos_ping.rexx
  plugins/modules/zos_tso_command.py
Labels: documentation

#71 Add an example that requires a command to be escaped
  plugins/modules/zos_operator.py
Labels: documentation
