Repository ansible-collections/ibm_zos_core, pull requests merged in 2020-11, with the labels that each got.

#208 Bugfix/4407/job utility fails on special chars
  plugins/module_utils/job.py
Labels: bugfix

#210 add dependency finder
  tests/dependencyfinder.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: enhancement

#209 Enhancement/4365/role doc support
  docs/Makefile
  docs/files/role_sample/defaults-main.yml
  docs/files/role_sample/doc_role_sample
  docs/files/role_sample/meta-main.yml
  docs/files/role_sample/role-doc-readme.txt
  docs/files/role_sample/role_sample.yml
  docs/files/role_sample/roles.rst
  docs/files/role_sample/tasks-main.yml
  docs/files/role_sample/vars-main.yml
  docs/scripts/role-sample-gen.sh
  docs/templates/role.rst.j2
Labels: documentation

#212 add origin/ to default branch name
  tests/dependencyfinder.py
Labels: bugfix

#213 Bugfix/4660/copy program objects
  plugins/modules/zos_copy.py
Labels: bugfix

#214 Update template to support complex list with elements
  docs/templates/module.rst.j2
Labels: documentation
