Repository ansible-collections/ibm_zos_core, pull requests merged in 2020-02, with the labels that each got.

#1 Initial collection commit for v0.0.1
  README.md
  __init__.py
  docs/README-ZOAU.md
  docs/README-python-zos.md
  docs/README-zos-data-set.md
  docs/README-zos-job-output.md
  docs/README-zos-job-query.md
  docs/README-zos-job-submit.md
  docs/README-zos-rexx-connection-plugin.md
  galaxy.yml
  playbooks/README.md
  playbooks/ansible.cfg
  playbooks/files/HELLO.jcl
  playbooks/group_vars/all.yml
  playbooks/inventory
  playbooks/zos-collection-sample.yaml
  plugins/.DS_Store
  plugins/__init__.py
  plugins/action/normal.py
  plugins/action/zos_job_submit.py
  plugins/connection/zos_ssh.py
  plugins/module_utils/.keep
  plugins/modules/__init__.py
  plugins/modules/zos_data_set.py
  plugins/modules/zos_job_output.py
  plugins/modules/zos_job_query.py
  plugins/modules/zos_job_submit.py
  tests/.DS_Store
  tests/__init__.py
  tests/conftest.py
  tests/helpers/.keep
  tests/helpers/__init__.py
  tests/helpers/ztest.py
  tests/requirements.txt
  tests/units/.DS_Store
  tests/units/__init__.py
  tests/units/modules/.DS_Store
  tests/units/modules/.keep
  tests/units/modules/__init__.py
  tests/units/modules/data_sets/.DS_Store
  tests/units/modules/data_sets/test_zos_data_set_unit.py
  tests/units/modules/jobs/test_job_submit.py
  tests/units/modules/jobs/test_zos_job_output.py
  tests/units/modules/jobs/test_zos_job_query.py
Labels: release

#2 Initial collection commit for v0.0.1 (#1)
  README.md
  __init__.py
  docs/README-ZOAU.md
  docs/README-python-zos.md
  docs/README-zos-data-set.md
  docs/README-zos-job-output.md
  docs/README-zos-job-query.md
  docs/README-zos-job-submit.md
  docs/README-zos-rexx-connection-plugin.md
  galaxy.yml
  playbooks/README.md
  playbooks/ansible.cfg
  playbooks/files/HELLO.jcl
  playbooks/group_vars/all.yml
  playbooks/inventory
  playbooks/zos-collection-sample.yaml
  plugins/.DS_Store
  plugins/__init__.py
  plugins/action/normal.py
  plugins/action/zos_job_submit.py
  plugins/connection/zos_ssh.py
  plugins/module_utils/.keep
  plugins/modules/__init__.py
  plugins/modules/zos_data_set.py
  plugins/modules/zos_job_output.py
  plugins/modules/zos_job_query.py
  plugins/modules/zos_job_submit.py
  tests/.DS_Store
  tests/__init__.py
  tests/conftest.py
  tests/helpers/.keep
  tests/helpers/__init__.py
  tests/helpers/ztest.py
  tests/requirements.txt
  tests/units/.DS_Store
  tests/units/__init__.py
  tests/units/modules/.DS_Store
  tests/units/modules/.keep
  tests/units/modules/__init__.py
  tests/units/modules/data_sets/.DS_Store
  tests/units/modules/data_sets/test_zos_data_set_unit.py
  tests/units/modules/jobs/test_job_submit.py
  tests/units/modules/jobs/test_zos_job_output.py
  tests/units/modules/jobs/test_zos_job_query.py
Labels: release

#4 Hotfix/122/fix readme url and license syntax
  README.md
  docs/README-ZOAU.md
  galaxy.yml
  playbooks/README.md
Labels: documentation, hotfix

#3 added arg parser to module_utils
  plugins/module_utils/better_arg_parser.py
Labels: enhancement

#10 Update content to reflect latest version
  README.md
  docs/README-ZOAU.md
  galaxy.yml
Labels: documentation

#9 Update colleciton with functional test cases
  tests/functional/__init__.py
  tests/functional/modules/test_zos_data_set_func.py
  tests/functional/modules/test_zos_job_output_func.py
  tests/functional/modules/test_zos_job_query_func.py
  tests/functional/modules/test_zos_job_submit_func.py
  tests/units/modules/.DS_Store
  tests/units/modules/__init__.py
  tests/units/modules/data_sets/.DS_Store
  tests/units/modules/test_zos_data_set_unit.py
  tests/units/modules/test_zos_job_output_unit.py
  tests/units/modules/test_zos_job_query_unit.py
  tests/units/modules/test_zos_job_submit_unit.py
Labels: enhancement

#6 refactor and patch job output checking
  plugins/module_utils/job.py
  plugins/modules/zos_job_output.py
  plugins/modules/zos_job_submit.py
Labels: hotfix

#14 updated job output for improved DD handling
  plugins/module_utils/job.py
  plugins/modules/zos_job_submit.py
Labels: bug

#15 Update/496/module security updates
  plugins/action/zos_job_submit.py
  plugins/module_utils/job.py
  plugins/modules/zos_data_set.py
  plugins/modules/zos_job_submit.py
  tests/functional/modules/test_zos_job_output_func.py
  tests/units/modules/test_zos_job_output_unit.py
  tests/units/modules/test_zos_job_submit_unit.py
Labels: bugfix, update
