Repository ansible-collections/ibm_zos_core, pull requests merged in 2020-03, with the labels that each got.

#17 Content/16/update module doc remove imports
  README.md
  plugins/module_utils/job.py
  plugins/modules/zos_data_set.py
  plugins/modules/zos_job_output.py
  plugins/modules/zos_job_query.py
  plugins/modules/zos_job_submit.py
  tests/requirements.txt
Labels: documentation

#18 Feature/76/ping module
  plugins/modules/zos_ping.rexx
  tests/conftest.py
  tests/functional/modules/test_zos_ping_func.py
Labels: enhancement

#21 Webdocs content for IBM z/OS Core Collection
  README.md
  README.rst
  docs/Makefile
  docs/source/community_guides.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/modules.rst
  docs/source/playbooks.rst
  docs/source/plugins.rst
  docs/source/quickstart.rst
  docs/source/release_notes.rst
  docs/source/requirements.rst
  docs/templates/module.rst.j2
  plugins/modules/zos_job_output.py
  plugins/modules/zos_job_query.py
Labels: documentation

#23 remove original_message return parameter
  docs/source/conf.py
  docs/source/installation.rst
  docs/source/plugins.rst
  plugins/modules/zos_job_output.py
  plugins/modules/zos_job_query.py
Labels: update

#25 Content/132/remove md files
  README.md
  README.rst
  docs/README-ZOAU.md
  docs/README-python-zos.md
  docs/README-zos-data-set.md
  docs/README-zos-job-output.md
  docs/README-zos-job-query.md
  docs/README-zos-job-submit.md
  docs/README-zos-rexx-connection-plugin.md
  docs/source/index.rst
  plugins/modules/zos_job_output.py
  plugins/modules/zos_job_submit.py
Labels: documentation

#27 Update/645/zos data set add catalog functionality
  plugins/module_utils/better_arg_parser.py
  plugins/module_utils/vtoc.py
  plugins/modules/zos_data_set.py
  tests/functional/modules/test_zos_data_set_func.py
  tests/requirements.txt
  tests/unit/modules/test_zos_data_set_unit.py
  tests/unit/modules/test_zos_job_output_unit.py
  tests/unit/modules/test_zos_job_query_unit.py
  tests/unit/modules/test_zos_job_submit_unit.py
Labels: update

#28 Update product name in webdocs
  README.rst
  docs/source/community_guides.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/playbooks.rst
  docs/source/plugins.rst
  docs/source/quickstart.rst
  docs/source/requirements.rst
  docs/templates/module.rst.j2
Labels: documentation

#29 Integraded document review comments
  docs/source/community_guides.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/playbooks.rst
  docs/source/plugins.rst
  docs/source/quickstart.rst
  docs/source/requirements.rst
  docs/templates/module.rst.j2
  galaxy.yml
  plugins/modules/zos_data_set.py
  plugins/modules/zos_job_output.py
  plugins/modules/zos_job_query.py
  plugins/modules/zos_job_submit.py
Labels: documentation

#32 Updates to documentation and galaxy configuration
  README.rst
  docs/source/index.rst
  docs/source/playbooks.rst
  docs/source/requirements.rst
  galaxy.yml
Labels: documentation

#34 Fix to README.rst duplicate wording
  README.rst
Labels: documentation

#35 Remove duplicate action plugins link
  docs/source/index.rst
Labels: documentation

#39 Corrected README to point to MD, and long tag removed
  galaxy.yml
Labels: bug, documentation

#40 Release v1.0.0
  .gitignore
  README.md
  docs/Makefile
  docs/README-ZOAU.md
  docs/README-python-zos.md
  docs/README-zos-data-set.md
  docs/README-zos-job-output.md
  docs/README-zos-job-query.md
  docs/README-zos-job-submit.md
  docs/README-zos-rexx-connection-plugin.md
  docs/source/community_guides.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/modules.rst
  docs/source/modules/zos_data_set.rst
  docs/source/modules/zos_job_output.rst
  docs/source/modules/zos_job_query.rst
  docs/source/modules/zos_job_submit.rst
  docs/source/playbooks.rst
  docs/source/plugins.rst
  docs/source/quickstart.rst
  docs/source/release_notes.rst
  docs/source/requirements.rst
  docs/templates/module.rst.j2
  galaxy.yml
  playbooks/README.md
  playbooks/group_vars/all.yml
  playbooks/zos-collection-sample.yaml
  plugins/.DS_Store
  plugins/action/normal.py
  plugins/action/zos_job_submit.py
  plugins/connection/zos_ssh.py
  plugins/module_utils/better_arg_parser.py
  plugins/module_utils/job.py
  plugins/module_utils/vtoc.py
  plugins/modules/zos_data_set.py
  plugins/modules/zos_job_output.py
  plugins/modules/zos_job_query.py
  plugins/modules/zos_job_submit.py
  tests/.DS_Store
  tests/conftest.py
  tests/functional/module_utils/test_arg_parser.py
  tests/functional/modules/test_module_security.py
  tests/functional/modules/test_zos_data_set_func.py
  tests/functional/modules/test_zos_job_output_func.py
  tests/functional/modules/test_zos_job_query_func.py
  tests/functional/modules/test_zos_job_submit_func.py
  tests/helpers/.keep
  tests/helpers/ztest.py
  tests/requirements.txt
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
  tests/unit/__init__.py
  tests/units/.DS_Store
  tests/units/__init__.py
  tests/units/modules/test_zos_data_set_unit.py
  tests/units/modules/test_zos_job_output_unit.py
  tests/units/modules/test_zos_job_query_unit.py
  tests/units/modules/test_zos_job_submit_unit.py
Labels: release

#48 Data Set Utility for Common Data Set Related Tasks
  plugins/module_utils/data_set_utils.py
Labels: enhancement

#49 Bugfix/832/fix non vsam non sms existence checking zos data set
  plugins/modules/zos_data_set.py
Labels: bugfix

#50 bugfix/822/determine-data-set-type
  plugins/module_utils/data_set_utils.py
Labels: bugfix

#51 Update/646/extended dynamic function support better arg parser
  plugins/module_utils/better_arg_parser.py
  tests/functional/module_utils/test_arg_parser.py
Labels: update

#52 update/822/data-set-utils
  plugins/module_utils/data_set_utils.py
Labels: update

#53 removed return block and unnecessary message field in module response
  plugins/modules/zos_data_set.py
Labels: documentation, update
