Repository ansible-collections/ibm_zos_core, pull requests merged in 2022-09, with the labels that each got.

#363 Enhancement/9108/zos Modify zos_encode functional test suite to not leave tmp files
  tests/dependencyfinder.py
  tests/functional/modules/test_zos_encode_func.py
Labels: Type: Enhancement

#365 enhancement/9108/zos_dataset_test_temp_files : Modify zos_data_set functional test suite to not leave tmp files
  tests/functional/modules/test_zos_data_set_func.py
Labels: Type: Enhancement

#366 Bugfix/364/zos blockinfile backupname
  plugins/modules/zos_blockinfile.py
  tests/functional/modules/test_zos_blockinfile_func.py
  tests/helpers/zos_blockinfile_helper.py
Labels: Type: Bug, Status: In Progress

#370 Enhancement/9108/zos_mvs_raw_test_files Modify zos_mvs_raw functional test suite to not leave tmp files
  tests/functional/modules/test_zos_mvs_raw_func.py
Labels: Type: Enhancement

#392 Issue/388/update gather facts docs
  plugins/modules/zos_gather_facts.py
  tests/functional/modules/test_zos_gather_facts_func.py
Labels: Type: Enhancement, Status: In Progress

#367 Bugfix/361/encoding into vsam
  plugins/module_utils/encode.py
  tests/functional/modules/test_zos_encode_func.py
Labels: Type: Bug, Status: In Progress

#368 Enhancement/9108/zos_job_output_test_files Modify zos_job_output functional test suite to not leave tmp files
  tests/functional/modules/test_zos_job_output_func.py
Labels: Type: Enhancement, Status: In Progress

#414 Bugfix/393/tmp hlq ddstatements: Adds tmphlq to create_temp datasets in DDStatements.
  changelogs/fragments/393-tmphlq-dd-statements.yml
  plugins/module_utils/dd_statement.py
  plugins/modules/zos_mvs_raw.py
Labels: Type: Enhancement
