Repository ansible-collections/ibm_zos_core, pull requests merged in 2022-10, with the labels that each got.

#462 [Bug] [zos_copy] Bugfixes for v1.3.6
  changelogs/fragments/462-copy-fetch-submit-utils.yml
  docs/source/modules/zos_apf.rst
  docs/source/modules/zos_mvs_raw.rst
  docs/source/release_notes.rst
  docs/source/requirements-single.rst
  galaxy.yml
  meta/ibm_zos_core_meta.yml
  plugins/connection/zos_ssh.py
  plugins/module_utils/job.py
  plugins/modules/zos_apf.py
  plugins/modules/zos_backup_restore.py
  plugins/modules/zos_blockinfile.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_data_set.py
  plugins/modules/zos_encode.py
  plugins/modules/zos_fetch.py
  plugins/modules/zos_job_submit.py
  plugins/modules/zos_lineinfile.py
  plugins/modules/zos_mvs_raw.py
  tests/dependencyfinder.py
  tests/functional/modules/test_zos_copy_func.py
  tests/helpers/zos_blockinfile_helper.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.9.txt
Labels: In Progress, Release

#306 Bugfix/8366/volume support zos copy
  CHANGELOG.rst
  changelogs/.plugin-cache.yaml
  changelogs/changelog.yaml
  changelogs/config.yaml
  changelogs/fragments/306-updates-zos-copy-architecture.yml
  changelogs/fragments/328-rename-retries-to-reconnection_retries.yml
  changelogs/fragments/v1.0.0_summary.yml
  changelogs/fragments/v1.0.0_summary_minor.yml
  changelogs/fragments/v1.0.0_summary_security.yml
  changelogs/fragments/v1.1.0_summary.yml
  changelogs/fragments/v1.1.0_summary_minor.yml
  changelogs/fragments/v1.2.1_summary.yml
  changelogs/fragments/v1.2.1_summary_bugs.yml
  changelogs/fragments/v1.2.1_summary_minor.yml
  changelogs/fragments/v1.3.0_summary.yml
  changelogs/fragments/v1.3.0_summary_bugs.yml
  changelogs/fragments/v1.3.0_summary_known.yml
  changelogs/fragments/v1.3.0_summary_minor.yml
  changelogs/fragments/v1.3.1_summary.yml
  changelogs/fragments/v1.3.1_summary_bugs.yml
  changelogs/fragments/v1.3.1_summary_known.yml
  changelogs/fragments/v1.3.3_summary.yml
  changelogs/fragments/v1.3.3_summary_bugs.yml
  changelogs/fragments/v1.3.4_summary.yml
  changelogs/fragments/v1.4.0-beta.1_summary.yml
  changelogs/fragments/v1.4.0-beta.1_summary_bugs.yml
  changelogs/fragments/v1.4.0-beta.1_summary_deprecated.yml
  changelogs/fragments/v1.4.0-beta.1_summary_minor.yml
  changelogs/fragments/v1.4.0-beta.1_summary_trivial.yml
  changelogs/fragments/v1.4.0-beta.2_summary.yml
  docs/source/modules/zos_apf.rst
  docs/source/modules/zos_copy.rst
  docs/source/modules/zos_fetch.rst
  docs/source/release_notes.rst
  galaxy.yml
  meta/execution-environment.yml
  meta/ibm_zos_core_meta.yml
  meta/runtime.yml
  plugins/action/zos_copy.py
  plugins/action/zos_fetch.py
  plugins/module_utils/backup.py
  plugins/module_utils/data_set.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_fetch.py
  requirements.txt
  tests/dependencyfinder.py
  tests/functional/modules/test_zos_apf_func.py
  tests/functional/modules/test_zos_copy_func.py
  tests/functional/modules/test_zos_fetch_func.py
  tests/functional/modules/test_zos_mount_func.py
  tests/helpers/zos_blockinfile_helper.py
  tests/pytest.ini
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.13.txt
  tests/sanity/ignore-2.9.txt
Labels: Bug, In Progress

#501 Bugfix zos_operator call in REXX code for SET keyword
  changelogs/fragments/501-allow-operator-set-command.yml
  docs/source/release_notes.rst
  plugins/modules/zos_operator.py
  tests/dependencyfinder.py
  tests/unit/test_zos_operator_unit.py
Labels: Bug, In Progress

#502 Bugfix zos_mount module where ccsid should have been a string type
  changelogs/fragments/502-update-ccsid-type-int.yml
  docs/source/release_notes.rst
  plugins/modules/zos_mount.py
Labels: Bug, In Progress

#493 Corrected typo in changelogs
  changelogs/fragments/341-update-collection-tmphlq.yml
  changelogs/fragments/393-tmphlq-dd-statements.yml
Labels: Documentation

#507 Bugfix - corrects the dd_name used in jobs.py
  changelogs/fragments/507-display-specific-ddname.yml
  docs/source/release_notes.rst
  plugins/module_utils/job.py
  tests/functional/modules/test_zos_job_output_func.py
Labels: Bug, In Progress

#511 Bugfix [zos_mount] ccsid type is string when it should be int, update dependency finder
  changelogs/fragments/511-update-ccsid-type-int.yml
  plugins/modules/zos_mount.py
  tests/dependencyfinder.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.13.txt
  tests/sanity/ignore-2.14.txt
  tests/sanity/ignore-2.9.txt
Labels: Bug, In Progress

#497 Bugfix/372/member backup name
  plugins/module_utils/backup.py
  tests/functional/modules/test_zos_blockinfile_func.py
Labels: Bug

#510 Fix job name in zos_job_output test case
  tests/functional/modules/test_zos_job_output_func.py
Labels: Bug, In Progress

#513 Update the forked ssh code to support both ansible 2.9 an 2.11
  changelogs/fragments/513-zos_ssh-support-ansible-2.11.yml
  plugins/connection/zos_ssh.py
  tests/dependencyfinder.py
Labels: Bug, In Progress

#491 Enhancement/tmp hlq zos data set
  changelogs/fragments/tmp-hlq-zos_data_set.yml
  plugins/module_utils/data_set.py
  plugins/modules/zos_data_set.py
  tests/functional/modules/test_zos_data_set_func.py
Labels: Enhancement

#522 Release/1.4.0 beta.2 pre release actions
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/306-updates-zos-copy-architecture.yml
  changelogs/fragments/501-allow-operator-set-command.yml
  changelogs/fragments/502-update-ccsid-type-int.yml
  changelogs/fragments/507-display-specific-ddname.yml
  changelogs/fragments/v1.4.0-beta.2_summary.yml
  docs/source/release_notes.rst
  plugins/action/zos_copy.py
  plugins/action/zos_fetch.py
  plugins/action/zos_job_submit.py
  plugins/module_utils/backup.py
  plugins/module_utils/job.py
  plugins/module_utils/zos_mvs_raw.py
  plugins/modules/zos_apf.py
  plugins/modules/zos_backup_restore.py
  plugins/modules/zos_blockinfile.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_data_set.py
  plugins/modules/zos_encode.py
  plugins/modules/zos_fetch.py
  plugins/modules/zos_job_output.py
  plugins/modules/zos_job_query.py
  plugins/modules/zos_job_submit.py
  plugins/modules/zos_lineinfile.py
  plugins/modules/zos_mount.py
  plugins/modules/zos_operator.py
  plugins/modules/zos_operator_action_query.py
  plugins/modules/zos_ping.py
  plugins/modules/zos_ping.rexx
  plugins/modules/zos_tso_command.py
Labels: Release

#519 Release v1.3.6
  docs/source/release_notes.rst
  docs/source/requirements_managed.rst
  plugins/action/zos_fetch.py
  plugins/action/zos_job_submit.py
  plugins/connection/zos_ssh.py
  plugins/module_utils/backup.py
  plugins/module_utils/zos_mvs_raw.py
  plugins/modules/zos_apf.py
  plugins/modules/zos_blockinfile.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_fetch.py
  plugins/modules/zos_job_output.py
  plugins/modules/zos_job_submit.py
  plugins/modules/zos_lineinfile.py
  plugins/modules/zos_operator.py
  plugins/modules/zos_tso_command.py
  tests/dependencyfinder.py
Labels: Release

#526 Update modules to correct lint errors and unused import from AnsibleModule
  plugins/modules/zos_data_set.py
  plugins/modules/zos_mount.py
Labels: Bug, In Progress, In Plan

#529 Release v1.4.0 beta.2
  CHANGELOG.rst
  changelogs/.plugin-cache.yaml
  changelogs/changelog.yaml
  changelogs/fragments/496-copy-support-directories.yml
  changelogs/fragments/v1.0.0_summary.yml
  changelogs/fragments/v1.1.0_summary.yml
  changelogs/fragments/v1.2.1_summary.yml
  changelogs/fragments/v1.3.0_summary.yml
  changelogs/fragments/v1.3.1_summary.yml
  changelogs/fragments/v1.3.3_summary.yml
  changelogs/fragments/v1.3.4_summary.yml
  changelogs/fragments/v1.4.0-beta.1_summary.yml
  changelogs/fragments/v1.4.0-beta.2_summary.yml
  docs/source/release_notes.rst
  plugins/modules/zos_fetch.py
Labels: Release

#546 Enable previously deprecated test cases for zos_operator and fix dependencyfinder
  changelogs/fragments/546-enable-zos_operator-func-test.yml
  tests/dependencyfinder.py
  tests/functional/modules/test_zos_operator_action_query_func.py
Labels: Enabler
