Repository ansible-collections/ibm_zos_core, pull requests merged in 2023-02, with the labels that each got.

#609 Bugfix/558/zos copy backup dev
  changelogs/fragments/588-zos_copy-emergency-backup.yml
  plugins/modules/zos_copy.py
Labels: Bug

#626 [1.5.0-beta.1] [zos_copy] Update/forward port from 1.4.0/Issues #553, #554, #560
  docs/source/modules/zos_copy.rst
  plugins/modules/zos_copy.py
  tests/functional/modules/test_zos_copy_func.py
Labels: Enhancement

#641 Bugfix/601 copy lib member 1.5.0
  changelogs/fragments/601-copy-loadlib-member.yml
  plugins/modules/zos_copy.py
Labels: Bug

#647 Corrects zos_data_set default record format FB breaking VSAM
  changelogs/fragments/647-zos_data_set_record_format.yml
  docs/source/modules/zos_data_set.rst
  plugins/modules/zos_data_set.py
  tests/conftest.py
Labels: Enabler

#659 Correct f-string usage to remain 2.7 compatible
  changelogs/fragments/588-zos_copy-emergency-backup.yml
  changelogs/fragments/588-zos_copy-emergenxy-backup.yml
  changelogs/fragments/599-copy-carriage-return.yml
  changelogs/fragments/600-zos_copy-special-characters.yml
  changelogs/fragments/601-copy-loadlib-member.yml
  changelogs/fragments/602-text-converter-import.yml
  changelogs/fragments/627-all-modules.yml
  changelogs/fragments/647-zos_data_set_record_format.yml
  changelogs/fragments/648-zos_operator-examples.yml
  changelogs/fragments/650-doc-meta-data-updates.yml
  changelogs/fragments/659-zos-lineinfile-f-string.yml
  changelogs/fragments/enhancement-518-text-converter-import.yml
  plugins/modules/zos_lineinfile.py
Labels: Bug, Documentation
