Repository ansible-collections/ibm_zos_core, pull requests merged in 2023-05, with the labels that each got.

#757 Bugfix/619/mode set for files applied test case
  tests/functional/modules/test_zos_copy_func.py
Labels: Bug

#747 Bugfix/381/failed when the job name was null or not found
  changelogs/fragments/747-failed_when_the_job_name_was_null_or_not_found.yaml
  plugins/module_utils/job.py
  tests/functional/modules/test_zos_job_output_func.py
Labels: Bug

#762 Bugfix/660/zos operator reported failure caused by unrelated error response messages
  changelogs/fragments/762-zos-operator-reported-failure-caused-by-unrelated-error-response.yaml
  plugins/modules/zos_operator.py
  tests/functional/modules/test_zos_operator_func.py
Labels: Changes Requested

#766 Replace prior tooling (makefile) that aidded the development workflow with a new 'ac' command.
  .gitignore
  Makefile
  ac
  changelogs/fragments/766-ac-command-replace-makefile.yml
  galaxy.yml
  make.env.encrypt
  scripts/hosts.env
  scripts/info.env.axx
  scripts/mount-shr.sh
  scripts/mounts.env
  scripts/mounts.sh
  scripts/profile-shr
  scripts/profile.sh
  scripts/requirements-2.11.env
  scripts/requirements-2.12.env
  scripts/requirements-2.13.env
  scripts/requirements-2.14.env
  scripts/requirements-2.9.env
  scripts/requirements-common.env
  scripts/requirements-latest.env
  scripts/venv.sh
Labels: Resolved

#778 347 new query fields
  plugins/module_utils/job.py
  plugins/modules/zos_job_query.py
  plugins/modules/zos_job_submit.py
  tests/functional/modules/test_zos_data_set_func.py
Labels: Enhancement, Waiting for reviewers

#780 Missing fragment in PR 778 New query fields
  changelogs/fragments/778-query-new-fields.yml
Labels: Documentation, Waiting for reviewers

#771 Update docs with ansible/ansible-core version, AAP and fix the dated git issue templates
  .github/ISSUE_TEMPLATE/bug_issue.yml
  .github/ISSUE_TEMPLATE/collaboration_issue.yml
  .github/ISSUE_TEMPLATE/doc_issue.yml
  .github/ISSUE_TEMPLATE/enabler_issue.yml
  .github/ISSUE_TEMPLATE/enhancement_feature.issue.yml
  .github/ISSUE_TEMPLATE/module_issue.yml
  README.md
  changelogs/771-update-ansible-version.yaml
  docs/source/release_notes.rst
Labels: Waiting for reviewers
