Repository ansible-collections/ibm_zos_core, pull requests merged in 2023-04, with the labels that each got.

#727 Update zos_blockinfile with complex examples
  changelogs/fragments/727-zos-blockinfile-examples.yml
  docs/source/modules/zos_blockinfile.rst
  plugins/modules/zos_blockinfile.py
Labels: Documentation

#728 zos_operator documentation escape example correction
  changelogs/fragments/728-zos_operator-example-updates.yml
  docs/source/modules/zos_operator.rst
  plugins/modules/zos_operator.py
Labels: Documentation

#725 Bugfix/678/1.5.0 encoding normalization zos copy
  changelogs/fragments/725-zos_copy-encoding-bugs.yml
  plugins/modules/zos_copy.py
  tests/functional/modules/test_zos_copy_func.py
Labels: In Progress

#718 zos_data_set - add force parameter to enable member delete via disp shr
  changelogs/fragments/358-zos-data-set-support-disposition-shr.yml
  plugins/module_utils/data_set.py
  plugins/modules/zos_data_set.py
  tests/functional/modules/test_zos_data_set_func.py
Labels: In Progress

#721 Add positional wildcard support to module zos_job_query
  changelogs/fragments/323-zos-job-query-handle-multiple-wildcards.yml
  docs/source/modules/zos_job_query.rst
  plugins/module_utils/job.py
  plugins/modules/zos_job_query.py
  tests/functional/modules/test_zos_job_query_func.py
Labels: In Progress

#640 Add and automate a load lib test case for module zos_copy
  changelogs/fragments/601-copy-loadlib-member.yml
  plugins/modules/zos_copy.py
  tests/functional/modules/test_zos_copy_func.py
Labels: Bug

#666 Add max_rc support for module zos_tso_command
  changelogs/fragments/666-zos_tso_command_maxrc.yml
  plugins/modules/zos_tso_command.py
  tests/functional/modules/test_zos_tso_command_func.py
Labels: In Progress, Changes Requested

#732 Fixes for #664 and #678 for 1.4.1
  changelogs/fragments/732-zos_copy-encoding-bugs.yml
  plugins/modules/zos_copy.py
  tests/functional/modules/test_zos_copy_func.py
Labels: In Progress

#734 Add and automate a load lib test case for module zos_copy
  changelogs/fragments/734-copy-loadlib-member-test-case.yml
  tests/functional/modules/test_zos_copy_func.py
Labels: In Progress

#736 Add copy lib member test case for 1.5.0
  changelogs/fragments/601-copy-loadlib-member.yml
  changelogs/fragments/641-copy-loadlib-member.yml
  tests/functional/modules/test_zos_copy_func.py
Labels: In Progress, Changes Requested

#739 zos_copy forward port a test case for symbols on a volume
  changelogs/fragments/739-zos_copy-volume-symbol-test.yml
  tests/functional/modules/test_zos_copy_func.py
Labels: Waiting for reviewers

#742 Bugfix/619/v1.4.1/zos copy mode fix
  changelogs/fragments/742_zos_copy-mode-is-applied-to-the-destination-directory-a-deviation-from-the-communtiy-module-behavior.yaml
  plugins/modules/zos_copy.py
Labels: Bug

#752 Merge release tasks for v1.5.0 into release branch
  CHANGELOG.rst
  README.md
  changelogs/.plugin-cache.yaml
  changelogs/changelog.yaml
  changelogs/fragments/641-copy-loadlib-member.yml
  changelogs/fragments/746--Mode-set-for-files-is-applied-to-destination-directory.yml
  changelogs/fragments/v1.5.0_summary.yml
  docs/source/release_notes.rst
  galaxy.yml
  meta/ibm_zos_core_meta.yml
  meta/runtime.yml
  plugins/module_utils/encode.py
  plugins/module_utils/job.py
  plugins/modules/zos_gather_facts.py
  tests/dependencyfinder.py
  tests/functional/modules/test_zos_copy_func.py
  tests/functional/modules/test_zos_job_submit_func.py
Labels: In Progress, Release

#731 Add force (disp=shr) option to zos_lineinfile and update zos_blockinfile with the same locking test case.
  changelogs/fragments/731-zos_linefile-disposition_share.yaml
  plugins/modules/zos_lineinfile.py
  tests/functional/modules/test_zos_blockinfile_func.py
  tests/functional/modules/test_zos_lineinfile_func.py
  tests/helpers/zos_blockinfile_helper.py
  tests/helpers/zos_lineinfile_helper.py
Labels: In Progress
