Repository ansible-collections/ibm_zos_core, pull requests merged in 2023-07, with the labels that each got.

#794 Bug fix, zos_copy returns an error message when a concurrent copy fails
  changelogs/fragments/794-zos_copy_report_error_message_when_concurrent_copy_fails.yaml
  plugins/modules/zos_copy.py
  tests/functional/modules/test_zos_copy_func.py
Labels: Do not Merge

#667 Enhancement/428/jinja2 template support
  changelogs/fragments/667-template-support.yml
  docs/source/modules/zos_copy.rst
  docs/source/modules/zos_job_submit.rst
  plugins/action/zos_copy.py
  plugins/action/zos_job_submit.py
  plugins/doc_fragments/template.py
  plugins/module_utils/template.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_job_submit.py
  tests/functional/modules/test_zos_copy_func.py
  tests/functional/modules/test_zos_job_submit_func.py
  tests/pytest.ini
Labels: Do not Merge

#755 Module zos_unarchive & zos_archive
  .github/ISSUE_TEMPLATE/enhancement_feature.issue.yml
  docs/source/modules/zos_archive.rst
  docs/source/modules/zos_unarchive.rst
  plugins/action/zos_unarchive.py
  plugins/module_utils/mvs_cmd.py
  plugins/modules/zos_archive.py
  plugins/modules/zos_unarchive.py
  tests/functional/modules/test_zos_archive_func.py
  tests/functional/modules/test_zos_unarchive_func.py
  tests/sanity/ignore-2.13.txt
  tests/sanity/ignore-2.14.txt
  tests/sanity/ignore-2.15.txt
Labels: Ready to merge

#896 Removed emergency backup and auto-recovery features.
  changelogs/fragments/696-zos-copy-remove-emergency-backup.yml
  plugins/modules/zos_copy.py
Labels: Enhancement, Ready to merge

#841 Enhance/839/add field to job query
  changelogs/fragments/839-Add-Field-to-zos-job-query.yml
  plugins/module_utils/job.py
  plugins/modules/zos_job_output.py
  plugins/modules/zos_job_query.py
  plugins/modules/zos_job_submit.py
Labels: Ready to merge

#840 Enhancement/850/Redesining test cases to be clearer
  changelogs/fragments/840-redesign-test-cases.yml
  tests/functional/modules/test_zos_blockinfile_func.py
  tests/functional/modules/test_zos_lineinfile_func.py
  tests/helpers/zos_blockinfile_helper.py
  tests/helpers/zos_lineinfile_helper.py
Labels: Changes Requested

#895 Functional tso command test cases currently can not be run concurrently#880
  changelogs/fragments/880-Functional_tso_command_test_cases_currently_can_not_be_run_concurrently.yml
  tests/functional/modules/test_zos_tso_command_func.py
Labels: Changes Requested

#906 Update make file doc generation with pre and post scripts for a subset of modules.
  changelogs/fragments/906-update-doc-generation.yml
  docs/Makefile
  docs/scripts/post-template.sh
  docs/scripts/post-zos_apf.sh
  docs/scripts/pre-template.sh
  docs/source/modules/zos_apf.rst
  docs/source/modules/zos_archive.rst
  docs/source/modules/zos_data_set.rst
  docs/source/modules/zos_job_output.rst
  docs/source/modules/zos_job_query.rst
  docs/source/modules/zos_job_submit.rst
  docs/source/modules/zos_unarchive.rst
  plugins/modules/zos_apf.py
  plugins/modules/zos_archive.py
Labels: Enabler, Waiting for reviewers

#911 Enhance/911/Improve-job-query-performance
  changelogs/fragments/911-Improve-job-query-performance.yml
  plugins/module_utils/job.py
  plugins/modules/zos_job_output.py
  plugins/modules/zos_job_query.py
  plugins/modules/zos_job_submit.py
Labels: Resolved
