Repository ansible-collections/ibm_zos_core, pull requests merged in 2023-06, with the labels that each got.

#789 Update ac command supporting files
  changelogs/fragments/789-ac-command-updates.yml
  scripts/hosts.env
  scripts/mounts.env
  scripts/requirements-2.15.env
Labels: Enabler

#772 Encode files recursively and test case for keep behavior.
  changelogs/fragments/772-Encode-files-recursively-and-test-case-for-keep-behavior.yml
  plugins/modules/zos_copy.py
  tests/functional/modules/test_zos_copy_func.py
Labels: Bug, Waiting for reviewers

#793 Update ac to support a single test
  ac
  changelogs/fragments/789-ac-command-add-test.yml
Labels: Enabler, Waiting for reviewers

#773 Return the dynamically created destination attributes
  changelogs/fragments/773-return-dynamically-created-dest-attrs.yaml
  plugins/action/zos_copy.py
  plugins/modules/zos_copy.py
  tests/functional/modules/test_zos_copy_func.py
Labels: Enhancement, Waiting for reviewers

#812 Add ansible-lint tooling added
  .ansible-lint
  ac
  changelogs/fragments/812-ansible-lint.yml
  galaxy.yml
  meta/runtime.yml
Labels: Waiting for reviewers

#813 Add ansible-lint tooling added
  .ansible-lint
  changelogs/fragments/813-ansible-lint.yml
  galaxy.yml
  meta/runtime.yml
Labels: Waiting for reviewers

#816 Update zos_data_set member description created
  changelogs/fragments/816-zos_data_set-update-vsam.yml
  docs/source/modules/zos_data_set.rst
  plugins/module_utils/data_set.py
  plugins/modules/zos_data_set.py
  tests/functional/modules/test_zos_data_set_func.py
  tests/sanity/ignore-2.16.txt
Labels: Waiting for reviewers

#814 Bugfix: Fixes zos_copy and zos_fetch deprecation msg for using _play_context.verbosity
  changelogs/fragments/814-zos_data_set-update-vsam-copy.yml
  plugins/action/zos_copy.py
  plugins/action/zos_fetch.py
  tests/conftest.py
  tests/functional/modules/test_zos_copy_func.py
  tests/helpers/ztest.py
Labels: Waiting for reviewers

#829 Release tasks v1.6.0
  .ansible-lint
  CHANGELOG.rst
  README.md
  changelogs/.plugin-cache.yaml
  changelogs/changelog.yaml
  changelogs/fragments/v1.6.0_summary.yml
  docs/source/release_notes.rst
  galaxy.yml
  meta/ibm_zos_core_meta.yml
  meta/runtime.yml
Labels: In Progress, Waiting for reviewers

#806 Bufix: Fixes zos_copy and zos_fetch deprecation msg for using _play_context.verbosity
  changelogs/fragments/791-zos_data_set-update-vsam-copy.yml
  changelogs/fragments/806-zos_copy_fetch-display-verbose.yml
  plugins/action/zos_copy.py
  plugins/action/zos_fetch.py
  tests/conftest.py
  tests/functional/modules/test_zos_copy_func.py
  tests/helpers/ztest.py
Labels: Waiting for reviewers
