Repository ansible-collections/ibm_zos_core, pull requests merged in 2023-12, with the labels that each got.

#1057 Bugfix/374/module zos mvs raw errors with long multi line quoted string in content field
  changelogs/fragments/1057-module_zos_mvs_raw_errors_with_long_multi_line_quoted_string_in_content_field.yml
  docs/source/modules/zos_mvs_raw.rst
  plugins/modules/zos_mvs_raw.py
Labels: Waiting for Response

#1079 [zos_copy] fix for executables copied from local fail with iconv error
  changelogs/fragments/1079-zos-copy-local-executable.yml
  plugins/modules/zos_copy.py
  tests/functional/modules/test_zos_copy_func.py
Labels: Waiting on Reviewers

#1042 [v1.9.0] Bugfix/837/missing ZOAU imports
  changelogs/fragments/1042-missing-zoau-imports.yml
  plugins/module_utils/import_handler.py
  plugins/module_utils/job.py
  plugins/modules/zos_job_query.py
  plugins/modules/zos_operator.py
Labels: Bug, Ready to Merge
