Repository ansible-collections/ibm_zos_core, pull requests merged in 2023-01, with the labels that each got.

#593 Update git issue slection field
  .github/ISSUE_TEMPLATE/bug_issue.yml
Labels: Documentation

#579 Bugfix/578/correct linting issues
  changelogs/fragments/579-zos-query-boolean-correction.yml
  galaxy.yml
  plugins/modules/zos_job_query.py
  tests/sanity/ignore-2.13.txt
Labels: Bug

#598 Update makefile and related artifacts with recent zVM changes
  Makefile
  make.env.encrypt
  scripts/mount-shr.sh.encrypt
  scripts/profile-shr.encrypt
Labels: Enabler

#613 Expand what is ingored for venv to all venv's
  galaxy.yml
Labels: Bug

#605 Added missing fragments for issues 309 and 408
  changelogs/fragments/309-replace-text-zos-encode.yml
  changelogs/fragments/408-restore-members-on-failure.yml
Labels: Documentation

#614 Update make file to read exported var VENV else default to 'venv'
  Makefile
Labels: Enabler
