Repository ansible-collections/ibm_zos_core, pull requests merged in 2023-08, with the labels that each got.

#918 Add test case to validate response come back complete
  changelogs/fragments/918-zos-operator-response-come-back-truncate.yaml
  tests/functional/modules/test_zos_operator_func.py
Labels: Waiting for reviewers

#939 Staging v1.7.0 beta.2
  CHANGELOG.rst
  changelogs/.plugin-cache.yaml
  changelogs/changelog.yaml
  docs/source/modules/zos_archive.rst
  docs/source/modules/zos_gather_facts.rst
  docs/source/release_notes.rst
  galaxy.yml
  meta/ibm_zos_core_meta.yml
  plugins/action/zos_unarchive.py
  plugins/modules/zos_archive.py
  tests/functional/modules/test_zos_archive_func.py
  tests/functional/modules/test_zos_unarchive_func.py
Labels: Release

#953 v1.7.0 beta.2 into dev
  CHANGELOG.rst
  changelogs/.plugin-cache.yaml
  changelogs/changelog.yaml
  docs/source/modules/zos_archive.rst
  docs/source/modules/zos_gather_facts.rst
  docs/source/release_notes.rst
  galaxy.yml
  meta/ibm_zos_core_meta.yml
  plugins/action/zos_unarchive.py
  plugins/modules/zos_archive.py
  tests/functional/modules/test_zos_archive_func.py
  tests/functional/modules/test_zos_unarchive_func.py
Labels: Waiting for reviewers

#804 Enhancement, improve load module and program object support in zos_copy
  changelogs/fragments/804-improved_load_module_and_program_object_support.yml
  plugins/action/zos_copy.py
  plugins/module_utils/copy.py
  plugins/modules/zos_copy.py
  tests/functional/modules/test_zos_copy_func.py
Labels: Changes Requested

#959 Updated mounts.evn with latests zoau mounts
  changelogs/fragments/959-ac-tool-update-mounts.yml
  scripts/mounts.env
Labels: Waiting for reviewers
