Repository ansible-collections/ibm_zos_core, pull requests merged in 2023-10, with the labels that each got.

#980 Added latest to allow member copy when disp=shr
  changelogs/fragments/980-zos-copy-disp-shr.yml
  plugins/action/zos_copy.py
  plugins/modules/zos_copy.py
  tests/functional/modules/test_zos_copy_func.py
Labels: Waiting for reviewers

#968 Initial commit to add LIBRARY to choices and docs
  changelogs/fragments/920-zos-copy-add-library-choice.yml
  docs/source/modules/zos_copy.rst
  plugins/modules/zos_copy.py
Labels: Bug, Documentation

#961 New module zos_script
  .github/ISSUE_TEMPLATE/bug_issue.yml
  .github/ISSUE_TEMPLATE/collaboration_issue.yml
  .github/ISSUE_TEMPLATE/doc_issue.yml
  .github/ISSUE_TEMPLATE/enabler_issue.yml
  .github/ISSUE_TEMPLATE/enhancement_feature.issue.yml
  docs/source/modules/zos_script.rst
  plugins/action/zos_script.py
  plugins/modules/zos_script.py
  tests/functional/modules/test_zos_script_func.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.13.txt
  tests/sanity/ignore-2.14.txt
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
  tests/sanity/ignore-2.9.txt
Labels: Module

#976 Enhancement/943/add wait zos operator and query
  changelogs/fragments/943-enhance-Add-wait-zos-operator-and-query.yml
  plugins/modules/zos_operator.py
  plugins/modules/zos_operator_action_query.py
  tests/functional/modules/test_zos_operator_action_query_func.py
  tests/functional/modules/test_zos_operator_func.py
Labels: Waiting for reviewers

#1029 Enabler/validate path join part 2
  changelogs/fragments/1029-validate-path-join.yml
  plugins/module_utils/template.py
  plugins/modules/zos_archive.py
  plugins/modules/zos_unarchive.py
Labels: Waiting for reviewers

#1027 main change to version checker for consolidation
  changelogs/fragments/1018-internal-consolidate-version-checks.yml
  plugins/module_utils/job.py
  plugins/module_utils/zoau_version_checker.py
  tests/functional/modules/test_zos_job_submit_func.py
Labels: Ready to merge

#1035 Add known issues doc for utf8 issues
  changelogs/fragments/1029-validate-path-join.yml
  changelogs/fragments/1034-document-utf8-known-issue.yml
  changelogs/fragments/918-zos-operator-response-come-back-truncate.yaml
  changelogs/fragments/934-Remove-conditional-unnecessary.yml
  changelogs/fragments/943-enhance-Add-wait-zos-operator-and-query.yml
  changelogs/fragments/951-Change-copy-for-zos-copy-and-remove-temporary-files.yml
  changelogs/fragments/952-zos-job-submit-truncate-final-character.yml
  changelogs/fragments/963-validate-path-join.yml
  changelogs/fragments/965-enhance-archive-tests.yml
Labels: Waiting for reviewers

#1028 [Enhancement] [zos_copy] Add support for ASA control chars
  changelogs/fragments/1028-asa-control-chars.yml
  docs/source/modules/zos_copy.rst
  docs/source/modules/zos_operator.rst
  docs/source/modules/zos_script.rst
  plugins/action/zos_copy.py
  plugins/module_utils/copy.py
  plugins/module_utils/data_set.py
  plugins/modules/zos_copy.py
  tests/functional/modules/test_zos_copy_func.py
  tests/pytest.ini
Labels: Waiting for reviewers
