Repository ansible-collections/ibm_zos_core, pull requests merged in 2024-01, with the labels that each got.

#1078 [Bugfix][v1.9.0]short job name sends back a value error with a full stack trace as the msg
  changelogs/fragments/1078-short_job_name_sends_back_a_value_error.yaml
  plugins/module_utils/better_arg_parser.py
  plugins/modules/zos_job_output.py
  plugins/modules/zos_job_query.py
  tests/functional/modules/test_zos_job_output_func.py
  tests/functional/modules/test_zos_job_query_func.py
Labels: Bug

#1176 [v1.9.0] [zos_copy] Enhancement/764/copy members
  changelogs/fragments/1176-copy-members.yml
  plugins/modules/zos_copy.py
  tests/functional/modules/test_zos_copy_func.py
Labels: Enhancement

#1195 [Conftest]Add_prefer_volumes_user
  changelogs/fragments/1195-Add_prefer_volumes_user.yml
  tests/conftest.py
  tests/helpers/volumes.py
Labels: Bug, Ready to Merge

#1169 [v1.10.0] [Enabler] [job] ZOAU v1.3.0 migration for job.py
  changelogs/fragments/1169-util-job-zoau-migration.yml
  plugins/module_utils/job.py
Labels: Enabler

#1187 [v1.10.0] [module_utils/copy.py] Implement ZOAU 1.3 migration changes into module_utils/copy.py
  changelogs/fragments/1187-migrate-module-utils-copy.yml
  plugins/module_utils/copy.py
Labels: Do not Merge

#1190 [v1.10.0] [module_utils/dd_statement.py] Implement ZOAU 1.3 migration changes into module_utils/dd_statement.py
  changelogs/fragments/1190-migrate-module_utils-dd_statement.yml
  plugins/module_utils/dd_statement.py
Labels: Do not Merge

#1188 [v1.10.0] [module_utils/backup.py] Implement ZOAU 1.3 migration changes into module_utils/backup.py
  changelogs/fragments/1188-migrate-module_utils-backup.yml
  plugins/module_utils/backup.py
Labels: Do not Merge, Changes Requested

#1182 [v1.10.0][module_utils/data_set.py] Implement ZOAU 1.3 migration changes into module_utils/data_set.py
  changelogs/fragments/1182-migrate-module-utils-data-set.yml
  plugins/module_utils/data_set.py
Labels: Do not Merge

#1184 [Enabler] [zos_copy] Remove zos_fetch call in loadlib test
  changelogs/fragments/1184-remove-zos-fetch-dep-from-zos-copy.yml
  tests/functional/modules/test_zos_copy_func.py
Labels: Do not Merge

#1189 [v1.10.0] [module_utils/encode.py] Implement ZOAU 1.3 migration changes into module_utils/encode.py
  changelogs/fragments/1189-migrate-module_utils-encode.yml
  plugins/module_utils/encode.py
Labels: Do not Merge
