Repository ansible-collections/ibm_zos_core, pull requests merged in 2024-02, with the labels that each got.

#1194 Cherry picked removed hard coded content from staging-v1.9.0-beta.1
  tests/conftest.py
  tests/functional/modules/test_zos_apf_func.py
  tests/functional/modules/test_zos_archive_func.py
  tests/functional/modules/test_zos_backup_restore.py
  tests/functional/modules/test_zos_blockinfile_func.py
  tests/functional/modules/test_zos_copy_func.py
  tests/functional/modules/test_zos_data_set_func.py
  tests/functional/modules/test_zos_encode_func.py
  tests/functional/modules/test_zos_fetch_func.py
  tests/functional/modules/test_zos_find_func.py
  tests/functional/modules/test_zos_job_query_func.py
  tests/functional/modules/test_zos_job_submit_func.py
  tests/functional/modules/test_zos_lineinfile_func.py
  tests/functional/modules/test_zos_mount_func.py
  tests/functional/modules/test_zos_mvs_raw_func.py
  tests/functional/modules/test_zos_tso_command_func.py
  tests/functional/modules/test_zos_unarchive_func.py
  tests/helpers/dataset.py
  tests/helpers/volumes.py
Labels: In Progress

#1210 Bugfix issue for zos_job_submit when location is not set
  changelogs/fragments/1016-remove-randint.yml
  changelogs/fragments/1036-apf-try-except.yml
  changelogs/fragments/1041-bug-zos-submit-job-honor-return-output-literally.yml
  changelogs/fragments/1042-missing-zoau-imports.yml
  changelogs/fragments/1043-bug-title-zos_operator-is-passing-wrong-value-to-zoauopercmd.yml
  changelogs/fragments/1045-local-uss-unarchive.yml
  changelogs/fragments/1048-Update_sanity_tests_ignore.yml
  changelogs/fragments/1048-update-ac-tool-pyyaml-version.yml
  changelogs/fragments/1049-xmit-temporary-data-sets.yml
  changelogs/fragments/1051-try-except-pass-zos_mvs_raw.yml
  changelogs/fragments/1052-try-except-pass-dd-statement.yml
  changelogs/fragments/1053-Enabler_1002_test_collections_on_ansible_core_2_16.yml
  changelogs/fragments/1055-remove-subprocess-encode.yml
  changelogs/fragments/1056-Update_sanity_ignore_2_16.yml
  changelogs/fragments/1057-module_zos_mvs_raw_errors_with_long_multi_line_quoted_string_in_content_field.yml
  changelogs/fragments/1060-remote_tmp_zos_script.yml
  changelogs/fragments/1064-corruped-second-copy.yml
  changelogs/fragments/1065-rexx-exec-tso_command.yml
  changelogs/fragments/1066-Mvs_to_non_existent_mvs_copy_destination_attrs_match_up.yml
  changelogs/fragments/1073-action_plugin_does_not_clean_up_remote_temporary_files_after_completion.yml
  changelogs/fragments/1074-improve-job-submit-error-msgs.yml
  changelogs/fragments/1077-modify-uss-extraction.yml
  changelogs/fragments/1078-short_job_name_sends_back_a_value_error.yaml
  changelogs/fragments/1089-update-managed_node_doc.yml
  changelogs/fragments/1091-Update_undocumented_argument_and_import_exception.yml
  changelogs/fragments/1101-fix-undefined-var.yml
  changelogs/fragments/1120-bugfix-zos_job_submit-default_value.yml
  changelogs/fragments/1158-Test-zos-fetch-find-remove-hardcoded-datasets.yml
  changelogs/fragments/1163-Refactor_calls_to_use_new_alias_and_execute_options.yml
  changelogs/fragments/1176-copy-members.yml
  changelogs/fragments/1195-Add_prefer_volumes_user.yml
  changelogs/fragments/1200-zos_backup_restore-sanity-issues.yml
  changelogs/fragments/977-remove-hard-coded-vols-and-datasets.yml
  changelogs/fragments/v1.9.0_summary.yml
  plugins/action/zos_job_submit.py
  tests/functional/modules/test_zos_job_submit_func.py
Labels: Backport, Port

#1222 [v1.10.0] [zos_copy] zos_copy migration to ZOAU v1.3.0
  changelogs/fragments/1222-zoau-migration-zos_copy.yml
  plugins/module_utils/job.py
  plugins/modules/zos_copy.py
  tests/functional/modules/test_zos_copy_func.py
  tests/functional/modules/test_zos_job_submit_func.py
Labels: Waiting on Reviewers

#1228 [v1.10.0][zos_find] Removed lineinfile dependency and test with ZOAU 1.3
  changelogs/fragments/1228-zos_find-remove-zos_lineinfile_dep.yml
  tests/functional/modules/test_zos_find_func.py
Labels: Waiting on Reviewers

#1229 [v1.10.0][zos_fetch] Migrate zos_fetch to ZOAU 1.3
  changelogs/fragments/1229-migrate-zos_fetch.yml
  plugins/modules/zos_fetch.py
  tests/functional/modules/test_zos_fetch_func.py
Labels: Waiting on Reviewers

#1215 [v1.10.0][Zos Operator Action Query]Migrate zos operator action query
  changelogs/fragments/1215-Migrate_zos_operator_action_query.yml
  plugins/modules/zos_operator_action_query.py
  tests/functional/modules/test_zos_operator_action_query_func.py
Labels: Waiting for Response

#1238 [v1.10.0][zos_unarchive] Migrate zos_unarchive to use ZOAU 1.3
  changelogs/fragments/1238-migrate-zos_unarchive.yml
  plugins/modules/zos_unarchive.py
  tests/functional/modules/test_zos_unarchive_func.py
Labels: Waiting on Reviewers

#1226 Update release notes for V3R1
  .github/ISSUE_TEMPLATE/bug_issue.yml
  .github/ISSUE_TEMPLATE/collaboration_issue.yml
  .github/ISSUE_TEMPLATE/doc_issue.yml
  .github/ISSUE_TEMPLATE/enabler_issue.yml
  .github/ISSUE_TEMPLATE/enhancement_feature.issue.yml
  .github/ISSUE_TEMPLATE/module_issue.yml
  docs/source/release_notes.rst
Labels: Waiting on Reviewers

#1216 [Enabler][1137]Validate_module_zos_job_output_migration_1.3.0
  changelogs/fragments/1216-Validate_module_zos_job_output_migration.yml
  plugins/module_utils/job.py
  plugins/modules/zos_job_output.py
  tests/functional/modules/test_zos_job_output_func.py
Labels: Waiting on Reviewers

#1236 [v1.9.0][zos_apf] Fix list operation only returning one data set
  changelogs/fragments/1236-bugfix-zos_apf-return-list.yml
  plugins/modules/zos_apf.py
Labels: Waiting on Reviewers
