Repository ansible-collections/ibm_zos_core, pull requests merged in 2024-04, with the labels that each got.

#1320 [Bugfix][1201]Zos_mvs_raw_ignores_tmp_hlq
  changelogs/fragments/1320-Zos_mvs_raw_ignores_tmp_hlq.yml
  plugins/module_utils/zos_mvs_raw.py
  plugins/modules/zos_mvs_raw.py
  tests/functional/modules/test_zos_mvs_raw_func.py
  tests/unit/test_zos_mvs_raw_unit.py
Labels: Waiting on Reviewers

#1364 Removed a test condition that obscured duration
  changelogs/fragments/1032-clean-job_submit-test.yml
  tests/functional/modules/test_zos_job_submit_func.py
Labels: Waiting on Reviewers

#1412 Updated actions to only run when PR is not draft
  .github/workflows/ac-ansible-test-sanity.yml
  .github/workflows/ac-bandit.yml
  .github/workflows/ac-galaxy-importer.yml
  .github/workflows/ac_changelog.yml
Labels: Waiting on Reviewers

#1322 [Documentation][encode] Add and standarize docstring to encode.py
  changelogs/fragments/1322-update-docstring-encode.yml
  plugins/module_utils/encode.py
Labels: Waiting on Reviewers

#1353 [Documentation][zos_job_query] Add docstrings to modules/zos_job_query.py
  changelogs/fragments/1353-update-docstring-zos_job_query.yml
  plugins/modules/zos_job_query.py
Labels: Do not Merge, Waiting on Reviewers

#1345 [Bugfix][1239][zos job submit]max_rc_more_than_0_doesn_not_put_change_as_true
  changelogs/fragments/1345-max_rc_more_than_0_doesn_not_put_change_as_true.yml
  plugins/modules/zos_job_submit.py
  tests/functional/modules/test_zos_fetch_func.py
  tests/functional/modules/test_zos_job_submit_func.py
Labels: Do not Merge, Waiting on Reviewers

#1443 [Bug][zos_find] Filter allocated space when using size filter
  changelogs/fragments/1443-zos_find-filter-size.yml
  plugins/modules/zos_find.py
  tests/functional/modules/test_zos_find_func.py
Labels: Waiting on Reviewers

#1350 [Documentation][zos_find] Add and standarize docstrings on modules/zos_find.py
  changelogs/fragments/1350-update-docstring-zos_find.yml
  plugins/modules/zos_find.py
Labels: Waiting on Reviewers

#1351 [Documentation][zos_gather_facts] Add and standarize docstrings on modules/zos_gather_facts.py
  changelogs/fragments/1351-update-docstring-zos_gather_facts.yml
  plugins/modules/zos_gather_facts.py
Labels: Do not Merge, Waiting on Reviewers

#1352 [Documentation][zos_job_output] Add and standarize docstrings on modules/zos_job_output.py
  changelogs/fragments/1352-update-docstring-zos_job_output.yml
  plugins/modules/zos_job_output.py
Labels: Do not Merge, Waiting on Reviewers

#1356 [Documentation][zos_mount] Add and standarize docstrings on modules/zos_mount.py
  changelogs/fragments/1356-update-docstring-zos_mount.yml
  plugins/modules/zos_mount.py
Labels: Waiting on Reviewers

#1354 [Documentation][zos_job_submit] Add and standarize docstrings on modules/zos_job_submit.py
  changelogs/fragments/1354-update-docstring-zos_job_submit.yml
  plugins/modules/zos_job_submit.py
Labels: Do not Merge, Waiting on Reviewers

#1453 Bugfix/1062/zos find pdse size error
  changelogs/fragments/1450-zos_find-filter-size-pdse.yml
  plugins/modules/zos_find.py
  tests/functional/modules/test_zos_find_func.py
Labels: Waiting on Reviewers, Port Backward

#1336 [Documentation][validation] Add docstrings to module_utils/validation.py
  changelogs/fragments/1336-update-docstring-validation.yml
  plugins/module_utils/validation.py
Labels: Waiting on Reviewers

#1333 [Documentation][job] Add docstrings to module_utils/job.py
  changelogs/fragments/1333-update-docstring-job.yml
  plugins/module_utils/job.py
Labels: Waiting on Reviewers

#1331 [Documentation][ickdsf] Add docstrings to module_utils/ickdsf.py
  changelogs/fragments/1331-update-docstring-ickdsf.yml
  plugins/module_utils/ickdsf.py
Labels: Waiting on Reviewers

#1332 [Documentation][import handler] Add docstrings to module_utils/import_handler.py
  changelogs/fragments/1332-update-docstring-import_handler.yml
  plugins/module_utils/import_handler.py
Labels: Waiting on Reviewers

#1383 Remove stack fault on longer running jobs
  changelogs/fragments/971-bug-job_submit-can-stacktrace.yml
  plugins/module_utils/job.py
  tests/functional/modules/test_zos_job_submit_func.py
Labels: Waiting on Reviewers
