Repository ansible-collections/ibm_zos_core, pull requests merged in 2024-03, with the labels that each got.

#1257 [zos_apf] Standardize ZOAU Imports
  changelogs/fragments/1257-zoau-import-zos_apf.yml
  plugins/modules/zos_apf.py
Labels: Waiting on Reviewers

#1202 [Enhancement] [Doc scripts] Modifed doc scripts to ensure compatibility between MacOS and GNU sed commands
  changelogs/fragments/1202-doc-gen-script-portability.yml
  docs/scripts/post-zos_apf.sh
  docs/scripts/pre-template.sh
Labels: Waiting on Reviewers

#1283 [v1.9.0] Collaboration 1246 to add typrun support for zos_job_submit
  changelogs/fragments/1246-bugfix-zos_job_submit-typrun.yml
  plugins/module_utils/job.py
  plugins/modules/zos_job_submit.py
  tests/functional/modules/test_zos_job_submit_func.py
Labels: Waiting on Reviewers

#1292 [v1.9.0] Add chained command example to zos_tso_command
  changelogs/fragments/1292-doc-zos_tso_command-example.yml
  docs/source/modules/zos_tso_command.rst
  plugins/modules/zos_tso_command.py
Labels: Waiting on Reviewers

#1296 [v1.9.0] Document the collections SFTP requirement and file tagging.
  changelogs/fragments/1296-doc-sftp-collection-requirements.yml
  docs/source/modules/zos_archive.rst
  docs/source/modules/zos_copy.rst
  docs/source/modules/zos_fetch.rst
  docs/source/modules/zos_job_submit.rst
  docs/source/modules/zos_script.rst
  docs/source/modules/zos_unarchive.rst
  docs/source/plugins.rst
  plugins/modules/zos_copy.py
  plugins/modules/zos_fetch.py
  plugins/modules/zos_job_submit.py
  plugins/modules/zos_script.py
  plugins/modules/zos_unarchive.py
Labels: Waiting on Reviewers

#1295 [v1.10.0-beta.1][port forward] Documentation to update zos_ping about the deprecated scp in OpenSSH 9 or later.
  changelogs/fragments/1295-doc-zos_ping-scp.yml
  docs/source/modules/zos_ping.rst
  plugins/modules/zos_ping.py
  plugins/modules/zos_ping.rexx
Labels: Waiting on Reviewers

#1293 [v1.10.0-beta.1][port forward] Add chained command example to zos_tso_command
  changelogs/fragments/1292-doc-zos_tso_command-example.yml
  docs/source/modules/zos_tso_command.rst
  plugins/modules/zos_tso_command.py
Labels: Waiting on Reviewers

#1294 [v1.9.0] Documentation to update zos_ping about the deprecated scp in OpenSSH 9 or later.
  changelogs/fragments/1294-doc-zos_ping-scp.yml
  docs/source/modules/zos_ping.rst
  plugins/modules/zos_ping.py
  plugins/modules/zos_ping.rexx
Labels: Waiting on Reviewers

#1288 [v1.9.0] [Backport] [zos_job_submit] Handling of non-UTF-8 chars
  changelogs/fragments/1288-job-submit-non-utf8-chars.yml
  plugins/module_utils/job.py
  tests/functional/modules/test_zos_job_query_func.py
  tests/functional/modules/test_zos_job_submit_func.py
Labels: Do not Merge

#1285 [v1.10.0] [Enabler] [zos_data_set] Enabler/992/fixsanityfourin110
  changelogs/fragments/992-fix-sanity4to6.yml
  plugins/module_utils/data_set.py
  plugins/modules/zos_data_set.py
  tests/functional/modules/test_zos_data_set_func.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.13.txt
  tests/sanity/ignore-2.14.txt
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
  tests/sanity/ignore-2.9.txt
Labels: Enabler, Waiting on Reviewers

#1300 [v1.10.0] [Bugfix] [zos_job_submit] Fix non-printable chars handling and testing in jobs
  plugins/module_utils/job.py
  tests/functional/modules/test_zos_job_submit_func.py
Labels: Port Forward

#1303 Pulled dev to un-comment data_set_func.py testing of committing non-existant files.
  tests/functional/modules/test_zos_data_set_func.py
Labels: Waiting on Reviewers

#1307 [Enabler] [zos_copy] Fix sanity issues and remove ignore files
  changelogs/fragments/1307-update-sanity-zos_copy.yml
  plugins/action/zos_copy.py
  plugins/modules/zos_copy.py
  tests/functional/modules/test_zos_copy_func.py
  tests/sanity/ignore-2.14.txt
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
Labels: Waiting on Reviewers
