Repository ansible-collections/ibm_zos_core, pull requests merged in 2025-03, with the labels that each got.

#1954 [zos_script][zos_copy] Support automatic removal of carriage return characters (CR) when copying files
  changelogs/fragments/1954-zos_copy-cr-removal-while-copying-file-to-remote.yml
  plugins/modules/zos_copy.py
  tests/functional/modules/test_zos_script_func.py
Labels: Do not Merge

#1963 [Documentation] Modify template generation to allow for attributes to be used.
  changelogs/fragments/1963-support-attributes-docs.yml
  docs/source/modules/zos_script.rst
  docs/templates/module.rst.j2
  plugins/modules/zos_script.py
Labels: Waiting on Reviewers

#1973 Update release 1.13.0 staging branch with the latest changes for docs.
  README.md
  docs/Makefile
  docs/ansible_content.rst
  docs/scripts/post-zos_apf.sh
  docs/scripts/pre-template.sh
  docs/source/_static/css/custom.css
  docs/source/_static/css/table.css
  docs/source/_static/my_theme.css
  docs/source/ansible_content.rst
  docs/source/character_set.rst
  docs/source/collection-requirements.rst
  docs/source/conf.py
  docs/source/configuration.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/license.rst
  docs/source/life-cycle.rst
  docs/source/modules/zos_apf.rst-e
  docs/source/modules/zos_ping.rst
  docs/source/playbooks.rst
  docs/source/reference/community.rst
  docs/source/reference/documentation.rst
  docs/source/release_notes.rst
  docs/source/requirements-single.rst
  docs/source/requirements_managed.rst
  docs/source/resources/character_set.rst
  docs/source/resources/releases_maintenance.rst
  docs/source/resources/resources.rst
  plugins/modules/__init__.py
  plugins/modules/zos_ping.py
Labels: Waiting on Reviewers, Ready to Merge

#1980 Update info environment with new zVMs
  scripts/hosts.env
Labels: Waiting on Reviewers

#1992 [Documentation][zos_data_set]Set all boolean parameters to false by default and update documentation
  changelogs/fragments/1992-zos_data_set-enable-by-default-attributes.yml
  plugins/modules/zos_data_set.py
Labels: Waiting on Reviewers

#1974 Update development branch with the same changes pushed to 1.13.0 (cherry-pick)
  README.md
  docs/Makefile
  docs/ansible_content.rst
  docs/scripts/post-zos_apf.sh
  docs/scripts/pre-template.sh
  docs/source/_static/css/custom.css
  docs/source/_static/css/table.css
  docs/source/_static/my_theme.css
  docs/source/ansible_content.rst
  docs/source/character_set.rst
  docs/source/collection-requirements.rst
  docs/source/conf.py
  docs/source/configuration.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/license.rst
  docs/source/life-cycle.rst
  docs/source/modules/zos_ping.rst
  docs/source/playbooks.rst
  docs/source/reference/community.rst
  docs/source/reference/documentation.rst
  docs/source/release_notes.rst
  docs/source/requirements-single.rst
  docs/source/requirements_managed.rst
  docs/source/resources/character_set.rst
  docs/source/resources/resources.rst
  plugins/modules/__init__.py
  plugins/modules/zos_ping.py
Labels: Waiting on Reviewers

#2000 Adding the check mode documentation
  changelogs/fragments/2000-documentation-for-check_mode-all-modules.yml
  plugins/modules/zos_apf.py
  plugins/modules/zos_archive.py
  plugins/modules/zos_backup_restore.py
  plugins/modules/zos_blockinfile.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_data_set.py
  plugins/modules/zos_encode.py
  plugins/modules/zos_fetch.py
  plugins/modules/zos_find.py
  plugins/modules/zos_gather_facts.py
  plugins/modules/zos_job_output.py
  plugins/modules/zos_job_query.py
  plugins/modules/zos_job_submit.py
  plugins/modules/zos_lineinfile.py
  plugins/modules/zos_mount.py
  plugins/modules/zos_mvs_raw.py
  plugins/modules/zos_operator.py
  plugins/modules/zos_operator_action_query.py
  plugins/modules/zos_ping.py
  plugins/modules/zos_script.py
  plugins/modules/zos_tso_command.py
  plugins/modules/zos_unarchive.py
  plugins/modules/zos_volume_init.py
  plugins/modules/zos_zfs_resize.py
Labels: Waiting on Reviewers
