Repository ansible-collections/ibm_zos_core, pull requests merged in 2025-02, with the labels that each got.

#1893 [Bug][zos_apf] Ensure idempotency in zos_apf when a library is added or removed
  changelogs/fragments/1893-zos_apf-fails-for-already-existing-file.yml
  plugins/module_utils/zoau_version_checker.py
  plugins/modules/zos_apf.py
  plugins/modules/zos_gather_facts.py
  tests/functional/modules/test_zos_apf_func.py
Labels: Waiting on Reviewers

#1904 [Bug][1.12.1] Fix zos_copy failing when copying asa characters into a data set with special chars in their name
  changelogs/fragments/1904-zos_copy-asa-special-char.yml
  plugins/module_utils/copy.py
  plugins/modules/zos_copy.py
  tests/functional/modules/test_zos_copy_func.py
Labels: Do not Merge

#1926 [1.13.0] Post release fixes into staging branch
  changelogs/fragments/1926-fix-beta-branch.yml
  docs/source/release_notes.rst
  tests/conftest.py
Labels: Waiting on Reviewers

#1925 [Enabler] [zos_job_submit] [zos_fetch] Fix invalid escape sequence that results in DeprecationWarning
  changelogs/fragments/1925-Deprecation-warning-zos-fetch-and-zos-job-submit.yml
  tests/functional/modules/test_zos_fetch_func.py
  tests/functional/modules/test_zos_job_submit_func.py
Labels: Enabler, Waiting on Reviewers

#1937 [Bug][1.13.0] Fix zos_copy failing when copying asa characters into a data set with special chars in their name
  changelogs/fragments/1924-zos_copy-asa-special-char.yml
  plugins/module_utils/copy.py
  plugins/modules/zos_copy.py
  tests/functional/modules/test_zos_copy_func.py
Labels: Waiting on Reviewers

#1933 When zos_blockinfile tries to introduce a block with double quotes generates a false negative
  changelogs/fragments/1933-zos_blockinfile-false_negative_double_quotes.yml
  plugins/modules/zos_blockinfile.py
  tests/functional/modules/test_zos_blockinfile_func.py
Labels: Waiting on Reviewers

#1941 [Bugfix] [Forward port] [zos_copy] Use of force_lock with ASA data sets
  changelogs/fragments/1941-zos_copy-asa-dest-lock-support.yml
  plugins/module_utils/copy.py
  plugins/modules/zos_copy.py
  tests/functional/modules/test_zos_copy_func.py
Labels: Do not Merge, Port Forward
