Repository ansible-collections/ibm_zos_core, pull requests merged in 2025-01, with the labels that each got.

#1810 [Enhancement] [zos_copy] [zos_job_submit] [zos_script] Add option to disable autoescape for Jinja templates
  changelogs/fragments/1810-autoescape-templates.yml
  docs/source/modules/zos_copy.rst
  docs/source/modules/zos_job_submit.rst
  docs/source/modules/zos_script.rst
  plugins/action/zos_copy.py
  plugins/action/zos_job_submit.py
  plugins/doc_fragments/template.py
  plugins/module_utils/template.py
  plugins/modules/zos_copy.py
  plugins/modules/zos_job_submit.py
  plugins/modules/zos_script.py
  tests/functional/modules/test_zos_copy_func.py
  tests/functional/modules/test_zos_job_submit_func.py
  tests/functional/modules/test_zos_script_func.py
Labels: Ready to Merge

#1767 [Module][1717]new_module_zfs_resize
  .github/ISSUE_TEMPLATE/bug_issue.yml
  .github/ISSUE_TEMPLATE/collaboration_issue.yml
  .github/ISSUE_TEMPLATE/doc_issue.yml
  .github/ISSUE_TEMPLATE/enabler_issue.yml
  .github/ISSUE_TEMPLATE/enhancement_feature.issue.yml
  plugins/module_utils/zfsadm.py
  plugins/modules/zos_zfs_resize.py
  tests/functional/modules/test_zos_zfs_resize_func.py
  tests/sanity/ignore-2.14.txt
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
  tests/sanity/ignore-2.17.txt
Labels: Module

#1852 [Bugfix] [zos_script] Fix how remote scripts permissions are handled
  changelogs/fragments/1852-zos_script-permissions.yml
  plugins/modules/zos_script.py
  tests/functional/modules/test_zos_script_func.py
  tests/helpers/ztest.py
Labels: Ready to Merge

#1868 Bugfix job submit ddbytecount - 1508
  changelogs/fragments/1508-fix-ddsl-size.yml
  plugins/module_utils/job.py
Labels: Bug

#1891 Added execution_time param in job response parameters
  changelogs/fragments/1891-zos_job_submit-include-execution_time.yml
  plugins/module_utils/job.py
  plugins/modules/zos_job_output.py
  plugins/modules/zos_job_query.py
  plugins/modules/zos_job_submit.py
  tests/functional/modules/test_zos_job_output_func.py
  tests/functional/modules/test_zos_job_query_func.py
  tests/functional/modules/test_zos_job_submit_func.py
Labels: Waiting on Reviewers
